### ISSUE TITLE
How to use graphene-sqlalchemy with Dataloader?

### ISSUE THREAD

**Issue by balthild** [graphql-python/graphene-sqlalchemy#106]
Should I define custom resolvers calling `xxx_loader.load(...)` in the class which extends `SQLAlchemyObjectType`? If so, what data I should return in DataLoader's `batch_load_fn()`? SQLAlchemy model objects or `graphene.ObjectType` objects?

**Comment by kigen** [comment]
@balthild Were you able to figure this out. 
I am looking at implementing Dataloaders to improve my query performance. 
Kindly share if you ever did.

**Comment by balthild** [comment]
@kigen It's more concerning the design of Python language. Python is duck-typing, so I could return an object for Any class, as long as the object contains those required attributes.

BTW, I'm not using graphene-sqlalchemy anymore. I've switched to MongoDB. :lol
