### ISSUE TITLE
Will the type graphene.ID of Mutation's input argument be resolved automatically?

### ISSUE THREAD

**Issue by leibiao** [graphql-python/graphene-sqlalchemy#107]
I test the code as follows
```
class Tags(SQLAlchemyObjectType):
    class Meta:
        model = models.Tags  # a SQLAlchemy model that contains two columns (id,name)
        interfaces = (graphene.relay.Node, )

class Test(graphene.Mutation):
    class Arguments:
        id = graphene.ID(required=True)
    ok = graphene.Boolean()

    def mutate(self, info, id):
        print id
        return Test(ok=True)

class Query(graphene.ObjectType):
    tags = SQLAlchemyConnectionField(Tags)

class Mutation(graphene.ObjectType):
   test = Test.Field()

schema = graphene.Schema(query=Query, mutation=Mutation)
```
I get a tag with result {"id":"VGFnczox","name":"test"}, and excute something as follows via GraphiQL console
```
mutation{
  test(id:"VGFnczox"){
    ok
  }
}
```
I find that the `print id` will ouput '**VGFnczox**' instead of a integer which is the id of tag in the database.So far, my testing has been limited to the GraphiQL console, so am I missing something?

**Comment by Fedalto** [comment]
I don't think you're missing anything.
As of now, there's nothing in place that resolves this (but I'd be great).
For now, you can fetch the objects using `graphene.Node.get_node_from_global_id()`

**Comment by leibiao** [comment]
@Fedalto Ok, I'll have a try. Thanks for your help.

**Comment by alexisrolland** [comment]
@leibiao I had the same need to convert graphene global Id (in your case `VGFnczox`) into the actual database Id, so that I can use it to query on the database and perform an update on a record.

I solved my issue like this but there might be a better way to do it using SQLAlchemy:

```
from graphql_relay.node.node import from_global_id
db_id = from_global_id(id)
print(db_id[1])
```

Note `from_global_id ` return a tuple `(type, id)`, this is why I print `db_id[1]` to print the integer value of my id only.

**Comment by leibiao** [comment]
@alexisrolland Thanks for you advice.Now I have adopted the method as @Fedalto mentioned that is same as yours,and everything works well.
