### ISSUE TITLE
How to filter the child of the main query?

### ISSUE THREAD

**Issue by afr-dt** [graphql-python/graphene-sqlalchemy#110]
I'm a relative newcomer to Graphene, I'm trying to make a query like this
Query example
```
{
   user(username: "Jon") { 
     name
     last_lame
     username
     posts(in_draft : true) { 
       title
       text
       in_draft
       update_at      
     }
   }
}
```
Filter the posts that are in draft. Is this possible?

Query:
```
class Query(graphene.ObjectType):

    user = graphene.Field(lambda: User, username=graphene.String())
    def resolve_user(self, info, username):
       query = User.get_query(info)
       return query.filter(UserModel.username == username).first()


   posts = graphene.List(lambda: Post, in_draft=graphene.Boolean())
   def resolve_posts(self, info, in_draft):
      query = Post.get_query(info)
      return query.filter(PostModel.in_draft == in_draft).all()
```

**Comment by flewellyn** [comment]
I also want to do these things, and have found that it does not work properly.  Graphene complains that the parameters are not found on the nested type.

**Comment by AdiFahmi** [comment]
Hi, any update on this?
I also need to achieve same thing

**Comment by aleks-fr** [comment]
Hi @AdiFahmi you can try to do the following your objects of type ```SQLAlchemyObjectType```

```
class Post(SQLAlchemyObjectType):
    class Meta:
        model = PostModel
        # interfaces = (relay.Node, )
```
In this case I'm getting the resolving of posts within the object user
```
class User(SQLAlchemyObjectType):

    class Meta:
        model = UserModel
        interfaces = (relay.Node, )

    posts = graphene.List(lambda: Post, in_draft=graphene.Boolean())
    def resolve_posts(self, info, in_draft):
      query = Post.get_query(info)
      return query.filter(PostModel.in_draft == in_draft).all()
```
And in the query just call the resolver of the user

```
class Query(graphene.ObjectType):

    user = graphene.Field(lambda: User, username=graphene.String())
    def resolve_user(self, info, username):
       query = User.get_query(info)
       return query.filter(UserModel.username == username).first()
```

**Comment by AdiFahmi** [comment]
Hi @aleks-fr thanks for the code

a question, why do i get "Received incompatible instance" when i'm using **.all()** in resolve_user?

**Comment by somada141** [comment]
Hi @aleks-fr, quick q re the code you provided above. While defining the `posts` under `User` allows one to nest them the `posts` wont' necessarily belong to the resolved `user`.

Is there a way to communicate the arguments of `resolve_user` to the nested `resolve_posts` so that posts can be limited to that user only?

**Comment by viktor992** [comment]
@somada141, it seems that `self` is the resolved `User`, so you could use `PostModel.user_id = self.id` to filter the posts.
```
class User(SQLAlchemyObjectType):

    class Meta:
        model = UserModel
        interfaces = (relay.Node, )

    posts = graphene.List(lambda: Post, in_draft=graphene.Boolean())
    def resolve_posts(self, info, in_draft):
      query = Post.get_query(info)
      return query.filter(PostModel.user_id = self.id, PostModel.in_draft == in_draft).all()
```

**Comment by erikwrede** [comment]
I am closing all old issues&PRs related to filtering. The discussion will continue in https://github.com/graphql-python/graphene-sqlalchemy/discussions/347 (WIP). A proposal for the implementation of filters is currently being worked on and will be posted there once it is ready.
