### ISSUE TITLE
When is the next release ?

### ISSUE THREAD

**Issue by kavink** [graphql-python/graphene-sqlalchemy#113]
@syrusakbary Its been a while since there has been an official release, Wondering when will there be a release, because mainly im interested in using #78

**Comment by paunovic** [comment]
@syrusakbary bump. Any ideas when the next official release will be?

**Comment by arlobryer** [comment]
+1 - looks like there's some really interesting improvements in the outstanding PRs. Particularly #78 and #98 (which is a necessary addition to the latter).
