### ISSUE TITLE
How do I query for a specific object based on ID using graphene?

### ISSUE THREAD

**Issue by santosh9991** [graphql-python/graphene-sqlalchemy#116]
When I try to fetch all customers and orders[Ref: Fig2] I get the response, but when I try to query for an individual Order I get the error[Ref: Fig1]. I do not get any error in the console. However, I get 400 response.

I get the following error when I run my code:

![image](https://user-images.githubusercontent.com/16803672/36654369-faf5bdaa-1a70-11e8-8a93-58f29f61900e.png)
Fig1: Error message
Code snippets 
![image](https://user-images.githubusercontent.com/16803672/36655209-12adf548-1a76-11e8-98a0-9b69891aa05d.png)

Fig2: schema.py
![image](https://user-images.githubusercontent.com/16803672/36654404-433f95f4-1a71-11e8-91ee-c23870e381ff.png)
Fig3: Models.py

**Comment by santosh9991** [comment]
I have updated  resolve_find_order method as follows(Fig4). I get different error now (Fig5)
 
![image](https://user-images.githubusercontent.com/16803672/36686191-823fc74c-1ada-11e8-8455-75d0f58d8866.png)
Fig4:

![image](https://user-images.githubusercontent.com/16803672/36686163-69b167ee-1ada-11e8-9ba7-f1db68bb8e86.png)
Fig5: Console error

**Comment by aleks-fr** [comment]
What version of graphene are you using?

**Comment by santosh9991** [comment]
2.0.1
Error was resolved after I replaced the code from Fig1 to Fig2. 
![image](https://user-images.githubusercontent.com/16803672/36759351-e6207954-1bcb-11e8-9bf7-6a71be4ae3b7.png)
Fig1: Previous code
![image](https://user-images.githubusercontent.com/16803672/36759374-004efce2-1bcc-11e8-9325-5161833aa43e.png)
Fig2: Current code

**Comment by aleks-fr** [comment]
Now in version 2 the resolvers are like this
```
    def resolve_find_order(self, info, order_id):
        query = Bank.get_query(info)
        return query.filter(OrderModel.oreder_id == oreder_id).first()
```

**Comment by brandonbrown4792** [comment]
Perhaps a little easier:

```
def resolve_find_order(self, info, order_id):
    OrderModel.objects.get(order_id=order_id)
```
