### ISSUE TITLE
Pagination example with page total and page number

### ISSUE THREAD

**Issue by Kazanz** [graphql-python/graphene-sqlalchemy#118]
I've successfully implemented offset/limit based pagination, see below.  But I need a page where the user can jump between the various pages, so I need to know the total items, as well as current page.  Cursor based pagination doesn't do this either, as it only knows the last and next page.  Can an example be provided for how to do this page type of pagination?  Is it possible?

```
 def resolve_tickets(self, info, **kwargs):
        offset = kwargs.pop('offset', 0)
        limit = kwargs.pop('limit', 10)
        return TicketType.get_query(info).filter_by(**kwargs).offset(offset).limit(limit).all()
```

**Comment by Kazanz** [comment]
My understanding is that you would use a [Connection](http://graphql.org/learn/pagination/#complete-connection-model)

**Comment by Kazanz** [comment]
This seems to be similiar issue to https://github.com/graphql-python/graphene-sqlalchemy/issues/58 and is solved via this PR https://github.com/graphql-python/graphene-sqlalchemy/pull/104'

Lets get it merged in

**Comment by hqman** [comment]
Hi  @Kazanz Could you show  a full example about offset base pagination include type defs ? Thanks!

**Comment by tz4678** [comment]
> I've successfully implemented offset/limit based pagination, see below. But I need a page where the user can jump between the various pages, so I need to know the total items, as well as current page. Cursor based pagination doesn't do this either, as it only knows the last and next page. Can an example be provided for how to do this page type of pagination? Is it possible?
> 
> ```
>  def resolve_tickets(self, info, **kwargs):
>         offset = kwargs.pop('offset', 0)
>         limit = kwargs.pop('limit', 10)
>         return TicketType.get_query(info).filter_by(**kwargs).offset(offset).limit(limit).all()
> ```

```python
class ConnectionField(SQLAlchemyConnectionField):
  """
  Добавляет человеческую постраничную навигацию вместо хуеты с first и after
  TODO: реализовать фильтры
  """

  def __init__(self, type, *args, **kw):
    super(ConnectionField, self).__init__(
        type, *args, page=graphene.Int(), per_page=graphene.Int(), **kw)

  @classmethod
  def get_query(cls, model, info, page=None, per_page=None, **kw):
    q = super(ConnectionField, cls).get_query(model, info, **kw)
    if per_page:
      q = q.limit(per_page)
    if page:
      q = q.offset((page - 1) * per_page)
    return q
```

Usage:

```graphql
query {
  contacts (page: 1, perPage: 10) {
    edges {
      node {
        id
        email
      }
    }
  }
}
```

**Comment by CSGrandeur** [comment]
without total_count, the pagination cannot be utilized correctly. Since we don't know how many pages there are.

however, with this "page", "per_page", the total_count by https://github.com/graphql-python/graphene-sqlalchemy/pull/104 would not be correct any more.

however again.. even with "after" and "first" we could get correct total_count, but we don't know "after what" with a given page number.
