### ISSUE TITLE
Any example of graphql query from flask app?

### ISSUE THREAD

**Issue by kavink** [graphql-python/graphene-sqlalchemy#119]
Basically I am very satisfied by my Front end doing graphql queries to the flask app with sqlalchemy backend. But from my flask app whenever I need to directly access my database I need to write sqlalchemy queries. Wondering if I just write graphql queries directly . something like Apollo frontend ecosystem.

Reason for this request is: I have almost figured out autogenerating Graphql queries and mutation from my data model, and would like just think and write as graphql queries and mutations from within my flask app. Any thoughts/comments if this is even right way to think about it?

**Comment by erikwrede** [comment]
You could use `schema.execute(gql_query,variable_values)` on your graphene schema to internally use your queries and mutations. 
More info: https://docs.graphene-python.org/en/latest/execution/execute/
