### ISSUE TITLE
Adding support for Postgres TSTZRANGE

### ISSUE THREAD

**Issue by gsvitak** [graphql-python/graphene-sqlalchemy#12]
Hello,

I need to be able to convert a postgres TSTZRANGE into a GraphQL type. I noticed that the graphene-django project does support the postgres range type.s 

Just curious if it would be a good idea to add the same support to this codebase.

https://github.com/graphql-python/graphene-django/blob/master/graphene_django/converter.py#L193

Thanks
G

**Comment by syrusakbary** [comment]
Completely! If you wanna work in a PR I will take a look it happily :)

**Comment by erikwrede** [comment]
You can add a converter yourself using the syntax detailed in https://github.com/graphql-python/graphene-sqlalchemy/pull/371
Additionally, we accept contributions that include new converters, too.
