### ISSUE TITLE
SQLAlchemyObjectType hides original SQLAlchemy exception

### ISSUE THREAD

**Issue by Fedalto** [graphql-python/graphene-sqlalchemy#121]
Hi all!

Here's a minimal code that explains the issue.

```py
import graphene
from graphene_sqlalchemy import SQLAlchemyObjectType
from sqlalchemy import Column, Integer
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship

Base = declarative_base()


class A(Base):
    __tablename__ = 'a'
    id = Column(Integer, primary_key=True)


class B(Base):
    __tablename__ = 'b'
    id = Column(Integer, primary_key=True)

    a = relationship(A)  # This is the breaking line


class BSchema(SQLAlchemyObjectType):
    class Meta:
        model = B


schema = graphene.Schema(query=BSchema)
```

When I try to run this file I only get this error:
```
Traceback (most recent call last):
  File "issue.py", line 22, in <module>
    class BSchema(SQLAlchemyObjectType):
  File "./.venv/lib/python3.6/site-packages/graphene/utils/subclass_with_meta.py", line 40, in __init_subclass__
    super_class.__init_subclass_with_meta__(**options)
  File "./.venv/src/graphene-sqlalchemy/graphene_sqlalchemy/types.py", line 97, in __init_subclass_with_meta__
    ).format(cls.__name__, model)
AssertionError: You need to pass a valid SQLAlchemy Model in BSchema.Meta, received "<class '__main__.B'>".
```

But I'm passing a valid SQLAlchemy Model in BSchema.Meta.

The problem is actually another. 
SQLAlchemy is raising this exception: 
```{NoForeignKeysError}Could not determine join condition between parent/child tables on relationship B.a - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression.```

But this exception is lost here https://github.com/graphql-python/graphene-sqlalchemy/blob/a2fe9263d73b3baccd63b192b983cda5abfb88f0/graphene_sqlalchemy/utils.py#L21-L27 (called from https://github.com/graphql-python/graphene-sqlalchemy/blob/a2fe9263d73b3baccd63b192b983cda5abfb88f0/graphene_sqlalchemy/types.py#L94)
making the debug process for a simple mistake a pain.

**Comment by cmcinroy** [comment]
This really makes troubleshooting model issues very difficult.
I hit this problem on a regular basis.

**Comment by DrPyser** [comment]
Yup, hit that problem too. It seems assertions are used a lot in the codebase, where proper exceptions would be more appropriate and yield more useful stack traces.

**Comment by dtamez** [comment]
It seems that this makes it impossible to use sqlalchemy-utils types.

**Comment by alefhsousa** [comment]
👍 I lost much time in troubleshooting to understand the real problem

**Comment by teelau** [comment]
Has anyone solved this?

**Comment by onlyanegg** [comment]
It seems like there are multiple solutions proposed for this. I was taking a look at this as well and was thinking of a different one. Something like the following. I was wondering why we are catching ArgumentError.

```python
def __init_subclass_with_meta__(...):
        ...
        if not is_mapped_class(model):
            raise Exception(
                'You need to pass a valid SQLAlchemy Model in {}.Meta, received "{}".'.format(
                    cls.__name__, model
                )
            )
        # assert is_mapped_class(model), (
        #    "You need to pass a valid SQLAlchemy Model in " '{}.Meta, received "{}".'
        # ).format(cls.__name__, model)
        ...

def is_mapped_class(cls):
    try:
        class_mapper(cls)
    except (UnmappedClassError):
    #except (ArgumentError, UnmappedClassError):
        return False
    else:
        return True

```

**Comment by vietvudanh** [comment]
God damn it. Why does this line not at least print out the stack trace? I spent 1 hours of finding what the caused before find out this issue.

**Comment by rmzr7** [comment]
@jkimbo can we merge #238 in?

**Comment by zacharyarnaise** [comment]
Seconded. This makes finding the root causes of errors troublesome.

**Comment by yesthesoup** [comment]
How annoying this is. For anyone else coming here with a Flask app, I had to comment out importing my graphqlview and schema.

in `myproject/__init__.py`

```python
...
#from myproject.routes.graphql import graphql_view
...

def create_app():
    ...
    #app.add_url_rule('/graphql', view_func=graphql_view())
```

in `myproject.routes.graphql`, where `schema.py` was the problem
```python
from flask_graphql import GraphQLView

from myproject.schema import schema
from myproject.routes.decorators import authentication_required

def graphql_view():
    return authentication_required(GraphQLView.as_view('graphql', schema=schema, graphiql=False))
```
this allowed me to `flask shell` without an error and when I tried to query a problematic model I got the real error.

**Comment by erikwrede** [comment]
As far as I can tell there are three separate PRs for this problem:

- https://github.com/graphql-python/graphene-sqlalchemy/pull/169
- https://github.com/graphql-python/graphene-sqlalchemy/pull/281

Which contain the same code except for some requested changes. And this PR, which simply drops all the assertions:

- https://github.com/graphql-python/graphene-sqlalchemy/pull/238/

Is there any preferred approach, and what's the status on requested changes? @connorbrinton @MPickfield @zefciu

**Comment by erikwrede** [comment]
@connorbrinton, thanks for the quick reply after such a long time!
I just gained access to this repo, so I can merge PRs and manage things. Still, I'm currently getting an overview of old and stagnant issues to see what was planned and ready to deploy, so any help or hints are highly appreciated!

**Comment by connorbrinton** [comment]
Neat! 😄 The conflicts aren't too difficult, so I went ahead and rebased my PRs and integrated the suggested changes. I also switched the git repository references in `.pre-commit-config.yaml`  from `git://` to `https://`, [since GitHub no longer supports the unauthenticated `git://` protocol](https://github.blog/2021-09-01-improving-git-protocol-security-github/)

Tests pass locally on my machine, so hopefully CI is happy with them as well 😂

**Comment by erikwrede** [comment]
Thanks! Looks good!
