### ISSUE TITLE
Invalid SQLAlchemy Model

### ISSUE THREAD

**Issue by rvandyk** [graphql-python/graphene-sqlalchemy#122]
Hey guys I hope someone can help me on this, i'm really stuck....

database automaping:
```
engine = create_engine(" blablabla", convert_unicode=True)

db_session = scoped_session(sessionmaker(autocommit=False,
                                         autoflush=False,
                                         bind=engine))

Base = automap_base()
Base.prepare(engine, reflect=True, generate_relationship=_gen_relationship, name_for_scalar_relationship = name_for_scalar_relationship, classname_for_table=camelize_classname, name_for_collection_relationship=pluralize_collection)

Buyer = Base.classes.Buyer

Base.query = db_session.query_property()
```

schema : 
```
import graphene
import json
from graphene import relay
from graphene_sqlalchemy import SQLAlchemyConnectionField, SQLAlchemyObjectType

from database import Buyer as BuyerModel

class Buyer(SQLAlchemyObjectType):

    class Meta:
        model = BuyerModel
        interfaces = (relay.Node, )

class Query(graphene.ObjectType):
    node = relay.Node.Field()
    all_buyers = SQLAlchemyConnectionField(Buyer)

schema = graphene.Schema(query=Query)
```

Produces the error : 
`AssertionError: You need to pass a valid SQLAlchemy Model in Buyer.Meta, received "<class 'sqlalchemy.ext.automap.Buyer'>".`

**Comment by Fedalto** [comment]
There's probably something wrong with your SQLAlchemy models, and nothing to do with the graphene schema.
I recently opened #121 explaining a bug that graphene-sqlalchemy does not show you the actual error. Your can try to put a breakpoint in `is_mapped_class` to see the exception SQLAlchemy is throwing.

**Comment by AndreCAndersen** [comment]
Thanks @Fedalto, I tried to dive in. Ultimately all `is_mapped_class(model)` does is call [`def manager_of_class(cls)`](https://github.com/zzzeek/sqlalchemy/blob/8f7766cc61479f3c9220c640230eeecd3d49ccc8/lib/sqlalchemy/orm/base.py#L208), in the `orm/base.py` module, using your defined model. It's a tiny function with does the following:

    def manager_of_class(cls):
        return cls.__dict__.get(DEFAULT_MANAGER_ATTR, None)

... where `DEFAULT_MANAGER_ATTR = '_sa_class_manager'`.

In essence it requires that you're model has a field '_sa_class_manager' if not it returns `None` then propagates the error up.

I don't think a class manager is set when you use reflection, i.e., through inheriting from `Base=automap_base()` when defining your models. I don't think there is anything wrong with @rvandyk's models, it's just that `graphene_sqlalchemy` assumes all SqlAlchemy models are structured the same, and it seems they aren't.

**Comment by dschmide** [comment]
I dont quite understand this response. As far as I can tell you only update the error assertion, then what was wrong about @rvandyk 's code? Should people use automap in conjunction with graphene-sqlalchemy or is this a bad approach? There is a lack of resources for this, thus I ended up here.

I use 
`metadate = db.MetaData(bind=engine)`
and then
`tablemodel = db.Table('table_name', metadata, autoload = true)`

can I use this tablemodel for graphql schemas? Imo, people working with existing databases really shouldnt be required to go through defining these models manually if they can "just" read them from the databases automatically. Does this technically work?

**Comment by Bulletninja** [comment]
> Thanks @Fedalto, I tried to dive in. Ultimately all `is_mapped_class(model)` does is call [`def manager_of_class(cls)`](https://github.com/zzzeek/sqlalchemy/blob/8f7766cc61479f3c9220c640230eeecd3d49ccc8/lib/sqlalchemy/orm/base.py#L208), in the `orm/base.py` module, the specified SqlAlchemy model class. It's a tiny function with does the following:
> 
> ```
> def manager_of_class(cls):
>     return cls.__dict__.get(DEFAULT_MANAGER_ATTR, None)
> ```
> 
> ... where `DEFAULT_MANAGER_ATTR = '_sa_class_manager'`.
> 
> In essence it requires that you're model has a field '_sa_class_manager' if not it returns `None` then propagates the error up.
> 
> I initially thought this was an issue with `graphene-sqlalchemy`, but now I've realized the error shows up because `Base.metadata.reflect(...)` wasn't called before using the models. In essence there was no metadata to work with.

Is there a way to make it call as soon as it is defined or is there another recommended solution? Right now i'm getting this error with very inconsistent behavior and i'm unable to debug it even if i put a breakpoint in that method 🤔

**Comment by aguaguilar** [comment]
Hello, I'm really late but I have a workaround to solve it.

`
class BuyerModel(Base):
    __table__ = Buyer
`

You can use it :-)

**Comment by flipbit03** [comment]
@aguaguilar can you clarify?

**Comment by abisek** [comment]
I ran into similar issue. I use `graphene-sqlalchemy` too but it may be a more common problem in sqlalchemy. It happens with two worded model names - FraudSignature, BuyerModel, etc. I had to explicitly define the relationship in models referring to two or more worded models. Similar associations with models with single word works.

```
class MyOtherClass(Base):
   #  buyer_models = relationship('BuyerModel')  # Did not work
   buyer_models = relationship('BuyerModel', primaryjoin='MyOtherClass.id == foreign(BuyerModel.my_other_class_id)',)

class BuyerModel(Base):
   ....
```
