### ISSUE TITLE
How to have field level schema for graphql ?

### ISSUE THREAD

**Issue by kavink** [graphql-python/graphene-sqlalchemy#123]
Basically as of now if a sql column is JSONString/JSONType, is it possible to also have schema for this column ? i.e. as of now when I do mutation for a field which requires json string, From client side I cannot do any validation. As I need to send it to Server for validation.

Wondering how can one have a graphql schema even for fields ? if its even possible ?

**Comment by erikwrede** [comment]
I think the way to go here would be to create a custom `ObjectType` for the JSON and deserialize the JSON into that Type.
Schemas for fields are not part of the GQL Spec. 
However, you could create and provide a JSON Schema outside of this library that you can check locally. 

This is an old issue, and my response should answer the question. If you have additional questions, feel free to reply anyway!
