### ISSUE TITLE
Allow writing a resolver that returns a SQLAlchemy as a relay connection

### ISSUE THREAD

**Issue by wichert** [graphql-python/graphene-sqlalchemy#132]
I would like to return a relay connection for queries. Using standard graphene-sqlalchemy you can do this:

```python
class Query(graphene.ObjectType):
    node = relay.Node.Field()

    all_users = SQLAlchemyConnectionField(User)
```

For various places where you need a more custom search the simplest approach is a custom resolver:

```python
class Query(graphene.ObjectType):
    node = relay.Node.Field()

    all_users = graphene.List(User)

    def resolve_all_users(self, info, **args):
        # Grab the root SQLAlchemy query
        query = User.get_query(info)
        return query.filter(
            User.active,
            # and possibly a whole bunch of other filters)
        ).options(joinedload(User.emails).all()
```

This works, but it returns a plain list of users without any support for pagination or other relay connection tricks handled by SQLAlchemyConnectionField. What I am looking for is a way to return a query, and have it automatically handled in a similar way as SQLAlchemyConnectionField does. Perhaps by introducing something like a `query_to_relay_connection` function you can use like this:

```python
class Query(graphene.ObjectType):
    node = relay.Node.Field()

    all_users = graphene.List(User)

    def resolve_all_users(self, info, **args):
        # Grab the root SQLAlchemy query
        query = User.get_query(info)
        query = query.filter(
            User.active,
            # and possibly a whole bunch of other filters)
        ).options(joinedload(User.emails)
        return query_to_relay_connection(query, User)
```

this can probably reuse a lot of code SQLAlchemyConnectionField currently uses internally.

**Comment by DrPyser** [comment]
I think you can return a query(or any iterable) from your custom resolver, while stll using a `SQLAlchemyConnectionField`, and it will work fine. The connection field will use the result from your custom resolver to construct connections.

**Comment by wichert** [comment]
Indeed, that works. I had actually discovered that as well but forgot to update the ticket.

**Comment by johnnymetz** [comment]
How did you get this to work?
