### ISSUE TITLE
[Flask Example] AttributeError: module 'graphene_sqlalchemy.utils' has no attribute 'sort_enum_for_model'

### ISSUE THREAD

**Issue by ericbahr** [graphql-python/graphene-sqlalchemy#142]
I tried to run the Flask-GraphQL example, using pipenv as my virtual environment/package manager, with python 3.

**Comment by radezet** [comment]
I have the same problem. I've tested it on Python 3.6 and 3.7 on 3 different machines (Linux/Windows) and everytime the same error occurs.

**Comment by kkroening** [comment]
Looks like the example code is newer than the version of `graphene-sqlalchemy` that's on pypi.

Here's how to install directly from your local git clone:
```
pip install -e ../..
```
(assuming you're running in the `examples/flask_sqlalchemy` directory in a clone of the repo; adjust accordingly otherwise)

**Comment by dtamez** [comment]
ha.  this is the second graphene-sqlalchemy example/tutorial in a row that I've tried and both were DOA.

**Comment by ericbahr** [comment]
It seems like we've identified the problem here (the pypi code is out of date). Should I close this issue?

**Comment by syrusakbary** [comment]
Just published a new version to PyPI: `2.1.0`.

Closing the issue :)
