### ISSUE TITLE
Support for hybrid_property?

### ISSUE THREAD

**Issue by gsvitak** [graphql-python/graphene-sqlalchemy#15]
Hello,

I am trying to use hybrid_property as a property on a GraphQL response. However, when I execute the GraphQL request, I am receiving an error stating the property cannot be found. 

Are SQlAlchemy hybrid_property attributes currently supported?

Thanks,
G

```
@hybrid_property
    def document_count(self):
        return len(self.linked_documents)
```

**Comment by kvey** [comment]
Looking into this and the main issue I see atm is what type the value of hybrid_property will have? Columns and relationships the types can be determined by their definitions, by hybird_property is pretty much dynamic.

**Comment by gsvitak** [comment]
Thanks.. 

How I worked around the problem was that I had to explicitly declare the GraphQl type via the hybrid method name in the schema and then make sure the SQLAlchemy returned the exact type in the hybrid method. Works for now.. but it would be great if the SQLAlchemy could handle automatically.

**Comment by syrusakbary** [comment]
This is now fixed in `master` (and upcoming version `2.0`). Closing the issue

**Comment by anisjonischkeit** [comment]
My hybrid property always returns a list of SQLAlchemy objects, how can I let graphene know about this so it doesn't just return a string?

**Comment by gsvitak** [comment]
Can you please provide a sample. Might be easier.

**Comment by anisjonischkeit** [comment]
```
# models.py

class Company(Base):
    __tablename__ = 'licence_revisions'

    id = Column(...)
    ...

    licence_states = relationship("Licence", back_populates="company", lazy="dynamic")

    @hybrid_property
    def latest_licence_states(self):
        db_session = object_session(self)

        return self.licence_states \
                   .order_by(Licence.uuid, Licence.revision_id) \
                   .distinct(Licence.uuid).all()

```


```
# query.py

class Licence(SQLAlchemyObjectType):
    ...

class Company(SQLAlchemyObjectType):
    class Meta:
        model = models.Company
        interfaces = (graphene.relay.Node, )


    # currently I need these lines to get it to work properly. if I leave them out I
    # just get a string representation of the list of  SQLAlchemy objects:
    # "[<models.Licence object at 0x7f073450ba90>, <models.Licence object at 0x7f073450bb10>]"

    latest_licence_states = SQLAlchemyConnectionField(Licence)
    def resolve_latest_licence_states(self, info):
        return self.latest_licence_states

class Query(graphene.ObjectType):
    node = graphene.relay.Node.Field()

    Company = graphene.Field(Company)
    def resolve_company(self, info):

        query = info.context["session"].query
        company = query(models.Company).get(COMPANY_ID)

        return company

```

I want to tell graphene-sqlalchemy that the returned type for the hybrid_property is a list of SQLAlchemy objects

**Comment by Salamek** [comment]
@anisjonischkeit Just probably late answer to your Q (and help anyone who google this as i did), i had similar problem with hybrid property that returned boolean, but graphene-sqlalchemy was casting it to string (`"true"` instead of `true`).
Only thing i had to do is set query return type in SQLAlchemyObjectType `is_managed = graphene.Boolean()`:

```python
class Subject(SQLAlchemyObjectType):
    # is_managed is hybrid property so we need to force the type
    is_managed = graphene.Boolean()

    class Meta:
        model = SubjectModel
        interfaces = (relay.Node, )
```

After this i get correct `is_managed: true` instead of `is_managed: "true"` in query response JSON

Not sure if this fix can help with your problem or not, but i guess you should use something like `graphene.List(Licence)`

**Comment by lkaupp** [comment]
@Salamek this should be mentioned in the official docs if using the hybrid property. Works like a charm!

Here some example code for graphene-flask-sqlalchemy for beginners - just for documentation:
`
//models/__init__.py
from flask_sqlalchemy import SQLAlchemy
db = SQLAlchemy()
//model.py
from sqlalchemy.ext.hybrid import hybrid_property
from backend.server.models import db

class CurrentListening(db.Model):
    __tablename__ = 'current_listening'
    id = db.Column(db.Integer, primary_key=True)
    depth = db.Column(db.String)
    _listening_endpoints = db.Column('listening_endpoints', db.String(), nullable=False, default='[]', server_default='[]')

    @hybrid_property
    def listening_endpoints(self):
        return json.loads(self._listening_endpoints)

    @listening_endpoints.setter
    def listening_endpoints(self, listening_endpoints):
        self._listening_endpoints = json.dumps(listening_endpoints)

//schema.py
class Listening(SQLAlchemyObjectType):
    class Meta:
        model = CurrentListening
        interfaces = (relay.Node, )

    listening_endpoints = graphene.List(graphene.String)

class ListeningQuery(graphene.ObjectType):
    listenings = SQLAlchemyConnectionField(Listening.connection)`

**Comment by flipbit03** [comment]
It'd be very nice if the hybrid_property translator could use the function's return type hints as the actual base for generating the final GraphQL type

**Comment by erikwrede** [comment]
@flipbit03 check out #333

**Comment by flipbit03** [comment]
I have opened a pull request for this in #340, satisfying most use cases with the types in the Standard Library and the List[T] container type. It also includes the ability to retrieve a previously generated SQLAlchemyObjectType.
