### ISSUE TITLE
abstract = True has been deprecated, plz update your example 

### ISSUE THREAD

**Issue by puorc** [graphql-python/graphene-sqlalchemy#157]
I tried a very simple subclass as described in your example from README but it doesn't work at all. 

```
class ActiveSQLAlchemyObjectType(SQLAlchemyObjectType):
    class Meta:
        abstract = True
    @classmethod
    def get_node(cls, info, id):
        return cls.get_query(info)

class Article(ActiveSQLAlchemyObjectType):
    class Meta:
        model = ArticleModel
        interfaces = (relay.Node,)
```
And Python complains "TypeError: Invalid attributes: abstract". So I am wondering whether there is other way I can do the same thing. Thank you!

**Comment by puorc** [comment]
Also I don't see a corresponding property in the source.
```
    def __init_subclass_with_meta__(
        cls,
        model=None,
        registry=None,
        skip_registry=False,
        only_fields=(),
        exclude_fields=(),
        connection=None,
        connection_class=None,
        use_connection=None,
        interfaces=(),
        id=None,
        _meta=None,
        **options
    ):
```

**Comment by adrianschneider94** [comment]
Just for reference: 'abstract' is defined in graphene.

https://github.com/graphql-python/graphene/blob/b0c8a17ec712ff8b332eb5e4227ce48dc8f439ea/graphene/utils/subclass_with_meta.py#L18

**Comment by erikwrede** [comment]
Examples will be overhauled in the future.
