### ISSUE TITLE
How to query by argument?

### ISSUE THREAD

**Issue by steinsag** [graphql-python/graphene-sqlalchemy#16]
I was wondering if querying a schema via specific arguments is supposed to work out of the box or if anything special must be done to make it work?

In case of the flask example, I was expecting the following to be a valid query:

    {
        role(roleId: 2) {
            roleId
            name
        }
    }

But I only get

> Unknown argument "roleId" on field "role" of type "Query".

So how would I need to extend the example so that I could search employees by their name or retrieve a role via the ID? Or is my query just wrong?

**Comment by cauyeung** [comment]
This worked for me following the Graphene docs. I think the Django Graphene project has some automatic filter support but I couldn't find the parallel implemented for this. You explicity define the arguments, in my case "pk". They then appear in your args in your resolve func where you can manually filter.

class Query(graphene.ObjectType):
  project = graphene.Field(ProjectType, pk=graphene.Int())

  def resolve_project(self, args, context, info):
    query = ProjectType.get_query(context)
    return query.get(args.get('pk'))

query = '''
  query {
    project(pk:1) {
      name
    }
  }
'''

**Comment by steinsag** [comment]
Mmh, ok, I assumed that this kind of automatic filtering is part of the SQL Alchemy / Graphene extension. I really would like to see that implemented, but I doubt I could figure out how to extend the library to do so :-(

**Comment by jkbbwr** [comment]
This seems rather limiting if this isn't supported

**Comment by dervos** [comment]
@steinsag You will need to update your Query in schema.py to:
```python
class Query(graphene.ObjectType):
    node = relay.Node.Field()
    all_employees = SQLAlchemyConnectionField(Employee)
    all_roles = SQLAlchemyConnectionField(Role)
    role = relay.Node.Field(Role)
```
This will allow you to select roles by id with:
```graphql
query Role($id: ID!){
  role(id: $id) {
    id
    name
  }
}
```

**Comment by kvey** [comment]
```query Role($roleId: ID!) {
  node(id: $roleId) {
    id
    ... on Role {
      id,
      name
    }
  }
}
```

Will work without additionally adding ` role = relay.Node.Field(Role)`. I'm not sure about the performance impact of this versus directly defining the Field.

**Comment by aminghadersohi** [comment]
+1 It would be great to have this.

**Comment by aminghadersohi** [comment]
So I get that you can query with the relay ID. But I want to query by something else. Like name. How do i do that?

**Comment by aminghadersohi** [comment]
I figured out how to do filtering for any field. I posted a possible solution here: https://github.com/graphql-python/graphene-sqlalchemy/issues/27

**Comment by erikwrede** [comment]
I am closing all old issues&PRs related to filtering. The discussion will continue in https://github.com/graphql-python/graphene-sqlalchemy/discussions/347 (WIP). A proposal for the implementation of filters is currently being worked on and will be posted there once it is ready.
