### ISSUE TITLE
Can I perform recursive queries?

### ISSUE THREAD

**Issue by davidsims9t** [graphql-python/graphene-sqlalchemy#18]
I have a database with a hierarchical recursive structure. This is what my schema looks like:

```
@schema.register
class HierarchyChild(SQLAlchemyNode):
    class Meta:
        model = HierarchyModel

@schema.register
class Hierarchy(SQLAlchemyNode):
    class Meta:
        model = HierarchyModel

    children = SQLAlchemyConnectionField(HierarchyChild)
```

Currently this returns nested results, however, it doesn't pass the parent context to the child node. Thanks in advanced!

**Comment by cliedeman** [comment]
Hi David

I had the same issue implementing a viewer pattern and then trying to use the parent context to filter child relations.

The root object is omitted from the [https://github.com/graphql-python/graphene-sqlalchemy/blob/master/graphene_sqlalchemy/fields.py#L26](call)

As a workaround you can subclass SQLAlchemyConnectionField and replace the connection_resolver method with one that passes the root to the get_query method.

The current pattern I use is to override get_query and apply all my custom filters and ordering.

@syrusakbary Would you be open to a PR that added the root to the get query method?

Ciaran

**Comment by davidsims9t** [comment]
Thanks @cliedeman, I'll give that a try. Do you have an example of how to do this? I'm new to using Python.

**Comment by cliedeman** [comment]
from graphene.relay.connection import PageInfo
	from graphql_relay.connection.arrayconnection import connection_from_list_slice

	import graphene
	from graphene import relay
	from graphene_sqlalchemy import SQLAlchemyConnectionField, SQLAlchemyObjectType

	class UserActivitiesConnectionField(SQLAlchemyConnectionField):
		def __init__(self):
			super().__init__(Activity)

		@classmethod
		def connection_resolver(cls, resolver, connection, model, root, args, context, info):
			"""
			Override Default method so that we can pass the root to the get_query method
			"""
			iterable = resolver(root, args, context, info)
			if iterable is None:
				iterable = cls.get_query(model, root, context, info, args)
			if isinstance(iterable, Query):
				_len = iterable.count()
			else:
				_len = len(iterable)
			return connection_from_list_slice(
				iterable,
				args,
				slice_start=0,
				list_length=_len,
				list_slice_length=_len,
				connection_type=connection,
				pageinfo_type=PageInfo,
				edge_type=connection.Edge,
			)

		# noinspection PyMethodOverriding
		@classmethod
		def get_query(cls, model: db_model.Activity, root: db_model.User, context, info, args):
			if not root:
				return []
			query.filter(model.user_id == root.id)
			return query

	class User(SQLAlchemyObjectType):
		class Meta:
			model = db_model.User
			interfaces = (relay.Node,)


Where `Activity` is some nested graphql object that needs the root

**Comment by davidsims9t** [comment]
@cliedeman Thanks for posting this. I ended up using upgrading to graphene 1.0 and using a lambda function to create a recursive nested relational ship on my Hierarchy schema.

**Comment by cliedeman** [comment]
Glad you got it working
Would you mind pasting a sample for future readers?

**Comment by davidsims9t** [comment]
Sure thing. It was pretty simple actually. So I just used:

`
class Hierarchy(SQLAlchemyObjectType):
    class Meta:
        model = HierarchyModel
        interfaces = (relay.Node, )

    children = SQLAlchemyConnectionField(lambda: Hierarchy)

    def resolve_children(self, args, context, info):
        return HierarchyModel.query.filter(HierarchyModel.parent_tsn.in_([self.tsn])).all()
`

If I use just use Hierarchy without using lambda, Hierarchy is undefined.
