### ISSUE TITLE
Create a new release which includes #154

### ISSUE THREAD

**Issue by jrast** [graphql-python/graphene-sqlalchemy#184]
The last release was quite some time ago. Shortly after the release #154 was implemented which contains a fix for Enum creation. Would it be possible to create a new release including the changes since the last relase?

**Comment by Nabellaleen** [comment]
I think we'll be able to release a new version soon, as soon as the broken build is fixed by #165

**Comment by Nabellaleen** [comment]
@syrusakbary : the [2.1.1](https://github.com/graphql-python/graphene-sqlalchemy/milestone/1) seems ready to release, could you do it ?

A 2.2 should also follow soon with some features which were in PR since a long time ;)
