### ISSUE TITLE
Development and Maintance of this package

### ISSUE THREAD

**Issue by brasilikum** [graphql-python/graphene-sqlalchemy#195]
Hey, it seems to me that this package is lacking People to maintain and develop it.
I come to this conclusion because many Issues go unanswered and Pull requests not merged.

What can we do about it? Who is willing to actively contribute in any way?
Are the current Maintainers willing to give some level of access to those people or should we gather around a fork?

**Comment by Nabellaleen** [comment]
New people are always welcome ;)

In fact, the whole project was a bit neglected for some months, but a new team is refreshing everything since a month, as mentioned on https://github.com/graphql-python/graphene/issues/884

You will also find more details on how to contribute by following this link

**Comment by jnak** [comment]
@brasilikum Feel free to request access to the Slack if you're interested in helping maintain this repo. Cheers.
