### ISSUE TITLE
Column `doc` keyword argument not converted for `id` field description

### ISSUE THREAD

**Issue by robinsonkwame** [graphql-python/graphene-sqlalchemy#205]
**Expected behavior:** the `doc` keyword argument to sqlalchemy.Column should be converted to a `description` for all fields types.

**Actual Behavior:** For `id` Columns the `doc` argument is not converted to a `description`.

**Steps to reproduce:**

Given the Flask example [here](https://github.com/graphql-python/graphene-sqlalchemy/tree/25dd3d01b719ceaf5286da4a7daf897387a15fc6/examples/flask_sqlalchemy) change [models.Department](https://github.com/graphql-python/graphene-sqlalchemy/blob/25dd3d01b719ceaf5286da4a7daf897387a15fc6/examples/flask_sqlalchemy/models.py#L7-L10) from
```
class Department(Base):
    __tablename__ = 'department'
    id = Column(Integer, primary_key=True)
    name = Column(String)
```
to
```
class Department(Base):
    __tablename__ = 'department'
    id = Column(Integer, primary_key=True, doc=" this is an id!")
    name = Column(String, doc=" this is a name! ")
```

run the example as expected (`python app.py`) and inspect the `Department` `name`, `id` fields in graphiql.

Only the name field reflects the unique doc string. The `name` field description says `this is a name!` but the `id field` says `The ID of the object.` when it should read ` this is an id!`

**Comment by erikwrede** [comment]
Can't reproduce. Seems to be fixed!
