### ISSUE TITLE
Bug "type object 'Employee' has no attribute 'sort_argument'"

### ISSUE THREAD

**Issue by royhananwar** [graphql-python/graphene-sqlalchemy#216]
I just clone this repo and try flask example
but when I try to run it without have any changing code
I got an error like this

`Traceback (most recent call last):
    File "./app.py", line 5, in <module>
    from schema import schema
  File "/home/examples/flask_sqlalchemy/schema.py", line 28, in <module>
    class Query(graphene.ObjectType):
  File "/home/examples/flask_sqlalchemy/schema.py", line 32, in Query
    Employee, sort=Employee.sort_argument())
AttributeError: type object 'Employee' has no attribute 'sort_argument'`

What should I do?

Thank you!

**Comment by Cito** [comment]
Are you sure you have the version from the cloned repo installed when running the app, not an older version?

**Comment by fatore** [comment]
I got the same here while following the steps from https://github.com/graphql-python/graphene-sqlalchemy/tree/master/examples/flask_sqlalchemy. 

I assumed the proper versions were defined in the [`requirements.txt`](https://github.com/graphql-python/graphene-sqlalchemy/blob/master/examples/flask_sqlalchemy/requirements.txt) file.

**Comment by Cito** [comment]
That `requirements.txt` file installs graphene-sqlalchemy from PyPI which is not compatible with the current development version. I think the `requirements.txt` file should be replaced with this:

```
-e ../../
Flask-GraphQL
```

That will install the currently checked out version. Graphene and SQLAlchemy will be automatically installed as dependency in a matching version. Only Flask-GraphQL needs to be installed explicitly.

Can you remove the virtualenv directory `env` and try again with that `requirements.txt` file?

**Comment by jnak** [comment]
Good point. There you go https://github.com/graphql-python/graphene-sqlalchemy/pull/218

**Comment by royhananwar** [comment]
> That `requirements.txt` file installs graphene-sqlalchemy from PyPI which is not compatible with the current development version. I think the `requirements.txt` file should be replaced with this:
> 
> ```
> -e ../../
> Flask-GraphQL
> ```
> 
> That will install the currently checked out version. Graphene and SQLAlchemy will be automatically installed as dependencies with matching versions. Only Flask-GraphQL needs to be installed explicitly and needs to be added in `requirements.txt`.
> 
> Can you remove the virtualenv directory `env` and try again with that `requirements.txt` file?

Yes, you are right. I need to use the old `requirements.txt`
Thank you!
it worked like charms!
