### ISSUE TITLE
Anything like DjangoFilterConnectionField

### ISSUE THREAD

**Issue by previa** [graphql-python/graphene-sqlalchemy#221]
Is there anything similar to DjangoFilterConnectionField? It seems  support filtering, pagination, mutation at same time. Is there alternative for graphene-sqlalchemy?

**Comment by jnak** [comment]
The closest equivalent is [SQLAlchemyConnectionField](https://github.com/graphql-python/graphene-sqlalchemy/blob/959458784ea25811a4941db0dedbaf7c3038dfc3/graphene_sqlalchemy/fields.py#L82).
