### ISSUE TITLE
ConnectionField causing expensive subquery

### ISSUE THREAD

**Issue by maged** [graphql-python/graphene-sqlalchemy#227]
This [line](https://github.com/graphql-python/graphene-sqlalchemy/blob/master/graphene_sqlalchemy/fields.py#L51) triggers a [count](https://docs.sqlalchemy.org/en/13/orm/query.html#sqlalchemy.orm.query.Query.count) of the connection query that loads the entire table into memory. This is v expensive for large tables, and defeats the purpose of using ConnectionFields for pagination.

Is there anyway to avoid this?

**Comment by maged** [comment]
Looks like postgresql handles these sub-queries well, so no need to change this.

**Comment by kuba-lilz** [comment]
The problem does exist with mysql backend. Whole table is loaded just to return count(*).
