### ISSUE TITLE
Best way to serialize "bytea" field?

### ISSUE THREAD

**Issue by vaskokj** [graphql-python/graphene-sqlalchemy#230]
I have a bytea field in a postgresql database. In my SQLAlchemy model it is defined as the following.

` checksum_sha256 = Column(LargeBinary, nullable=False, unique=True)`

When I query for this in graphiQL the server side throw the error.

`TypeError: Object of type 'bytes' is not JSON serializable`

This is a pretty obvious solution as it can't serialize the data. Is there any way to handle this appropriately?

**Comment by flewellyn** [comment]
Perhaps by translating it to base64?

**Comment by jnak** [comment]
Have you tried redefining the field on your `SQLAlchemyObjectType` subclass?
```
class YourModel(SQLAlchemyObjectType)
    class Meta:
        ...
    
     checksum_sha256 = grapheme.Field(graphene.String)
```
That should override the field auto-generated by `graphene-sqlalchemy`.

**Comment by vaskokj** [comment]
@jnak That works! Thanks a ton!
