### ISSUE TITLE
can I query with a field parameter on a subrelation

### ISSUE THREAD

**Issue by vaskokj** [graphql-python/graphene-sqlalchemy#232]
I am trying to figure out how I can accept a parameter and query on that field in a sub table in a GraphQL query. 

This is an example.

    query{
      allModels{
        edges{
          node{
            featureVectors(featureSize: 128){ #I want to query on this
              edges{
                node{
                  modelSize
                  featureVectors
                }
              }
            }
          }
        }
      }
    }

Here is that I'm using to query the data. It works to query the data, except that I would like to be able to pass a parameter to search for a specific for example, featureVectors(featureSize: 128). I can't seem to find anything in the Graphene-SQLAlchemy library to allow this natively. 

    class ModelModel(Base):
        __tablename__ = 'models'
    
        id = Column(Integer, primary_key=True, server_default=text("nextval('models_id_seq'::regclass)"))
        type = Column(Text)
        components = Column(Float)
        notes = Column(Text)
        feature_vectors = relationship("FeatureVector", back_populates='models')
    
    class FeatureVectorModel(Base):
    
        id = Column(BigInteger, primary_key=True, server_default=text("nextval('feature_vectors_id_seq'::regclass)"))
        model_size = Column(Integer)
        feature_vectors = Column(ARRAY(Float(precision=53)))
    
        models = relationship('Model', back_populates='feature_vectors')
    
    class Model(SQLAlchemyObjectType):
        class Meta:
            model = ModelModel
            interfaces = (relay.Node, )
    
    
    class ModelConn(relay.Connection):
        class Meta:
            node = Model
    
    
    class Query(graphene.ObjectType):
        node = relay.Node.Field(schema_cadlearn.Model)
        all_models = SQLAlchemyCon

**Comment by flarco** [comment]
+1

**Comment by jnak** [comment]
No there is none at the moment in `graphene-sqlalchemy`. We ran into a similar issue at my company and ended up implementing a subclass of `graphene.Field` that does just that. 

The main idea is to allow connection fields to take a `SQLAlchemy` query object and some variables so you can do something like that:
```
def get_query_for_feature_vector(_root, info, feature_size):
   return FeatureVector.get_query(info).filter(FeatureVectorModel.model_size == feature_size)

class Model(SQLAlchemyObjectType):
     class Meta:
         ....
      
      feature_vectors = SQLConnectionField(
            FeatureVector._meta.connection,
             get_query_for_feature_vector,
             feature_size=graphene.Integer(),
      )

```

We are not planning to open-source it in the immediate future but we might prioritize it if there is demand. I'm going to close the ticket for now and let people upvote this comment to express their interest in this.
