### ISSUE TITLE
Custom Object Marshalling

### ISSUE THREAD

**Issue by vishalkuo** [graphql-python/graphene-sqlalchemy#255]
Hi there, does graphene-sqlalchemy support overriding the automapper to allow us to map resolved ORM objects to custom db objects?

As an example, I'd like a graphsql schema of the following:
```
class MyCustomObject(graphene.ObjectType):
  customField = Field(String)
```

and my ORM object:
```
class MyDBObject(db.Model):
  str_field = db.Column(db.String(128))
```

Now if I query MyCustomObject:
```
{
  my_custom_objects {
    customField
  }
}
```

I want to be able to map the custom object fields to my db object, return my db objects, and have them mapped back to `MyCustomObject`. 

I'm fairly new to graphql and graphene, so I apologize in advance if this is an extremely basic connection or if this isn't how graphql is meant to work. 

Note: the reason I'm apprehensive of just mapping the field in the resolver is that we have to return `MyDBObject.query.all()` which will be expensive to serialize

**Comment by jnak** [comment]
Currently there are 2 ways.

The most simple is this:
```
class MyCustomObject(graphene.SQLAlchemyObjectType):
    class Meta(object):
        model = MyDBObject

  customField = Field(String)

  def resolve_custom_field(obj, ...):
      return obj.str_field
```

There is another way not yet documented:
```
class MyCustomObject(graphene.SQLAlchemyObjectType):
   ...

  customField = ORMField(model_attr='str')
```

I don't follow your point on `MyDBObject.query.all()`.  This logic that selects the objects needs to be in a root level resolver in your example:
```
class Query(graphene.SQLAlchemyObjectType):
  my_custom_objects = List(MyCustomObject)

  def resolve_my_custom_objects(...):
      return MyDBObject.query.all()   # You would add filtering here
```

Hope that helps!
