### ISSUE TITLE
Exception: Don't know how to convert the SQLAlchemy field: UUIDType

### ISSUE THREAD

**Issue by Msordet** [graphql-python/graphene-sqlalchemy#257]
Hi,

My app crashes with the following mapping:
```python
#error
Exception: Don't know how to convert the SQLAlchemy field item.uuid_column (<class 'sqlalchemy.sql.schema.Column'>)

# model
from sqlalchemy_utils import UUIDType

class Item(Base):
    uuid_column = Column(UUIDType(binary=False), nullable=False, unique=True)

# schema
from graphene_sqlalchemy import SQLAlchemyObjectType

class ItemNode(SQLAlchemyObjectType):
    class Meta:
        model = Item
```

I tried to put this in my schema file to no avail:
```python
from sqlalchemy_utils import UUIDType
from graphene_sqlalchemy.converter import get_column_doc, is_column_nullable, convert_sqlalchemy_type

@convert_sqlalchemy_type.register(UUIDType)
def convert_column_to_string(type, column, registry=None):
    return graphene.String(description=get_column_doc(column), required=not (is_column_nullable(column)))
```

I checked the following issues/PR but I don't get it: :/ 
* https://github.com/graphql-python/graphene-sqlalchemy/issues/53
* https://github.com/graphql-python/graphene-sqlalchemy/issues/233
* https://github.com/graphql-python/graphene-sqlalchemy/pull/203

Can someone point me in the right direction with this?

**Comment by Msordet** [comment]
I found a solution by putting the `convert_column_to_string` right after the model declaration instead of in the schema file.
I don't really get why so if someone could explain, that'd be nice. :)

**Comment by jbvsmo** [comment]
This still doesn't work for me with the error:

`Exception: NonNull could not have a mounted String() as inner type. Try with NonNull(String).`

Trying with `NonNull(String)` give another error

`AssertionError: Can only create NonNull of a Nullable GraphQLType`

**Comment by jbvsmo** [comment]
The above error happens when I set `primary_key=True` on the column. 
I don't see why an UUID could not be the primary_key, but seems like this is an issue with graphene-sqlalchemy treating as string, since the model works fine

**Comment by calibodhi** [comment]
Any updates on this issue? I am trying to use a UUID as a primary key and having the same error as the original above. Many thanks :pray:

**Comment by rrobby86** [comment]
Using [this](https://docs.sqlalchemy.org/en/14/core/custom_types.html#backend-agnostic-guid-type) custom SQLAlchemy type using UUID objects on Python side, on graphene 3.1.1 and **graphene-sqlalchemy 3.0.0b3** (other versions may differ) I managed to get proper conversion to string without errors adding the following before declaring GraphQL schema (i.e. `SQLAlchemyObjectType` subclasses):

```
from graphene_sqlalchemy.converter import convert_sqlalchemy_type
from my.own.sub.package import GUID

@convert_sqlalchemy_type.register(GUID)
def convert_uuid_to_string(type, column, registry=None):
    return String
```

Using `String(description=..., required=...)` as suggested above was giving me an error `NonNull could not have a mounted String() as inner type. Try with NonNull(String).`
