### ISSUE TITLE
Is there a right pagination suggestion？

### ISSUE THREAD

**Issue by CSGrandeur** [graphql-python/graphene-sqlalchemy#258]
pagination needs  page, per page and total count

however,  with https://github.com/graphql-python/graphene-sqlalchemy/issues/118, we can only use "page" and "per_page", but the total_count by https://github.com/graphql-python/graphene-sqlalchemy/pull/104 would not be correct any more.

with "after" and "first", we could get correct total_count. But we don't know "after what" with a given page number.

for example, there are totally 10,000 items. With a filter, we get 8,000 items. 
set per page to 100, given page 12, we need the filtered 1101~1200 item.

with https://github.com/graphql-python/graphene-sqlalchemy/pull/104 , we got total_number 100 rather than 8,000, then we could not print the right total page num (80).

with "after" and "first", we don't know "after what" to get page 12. because the items are filtered, the IDs are not continuously.

**Comment by Bulletninja** [comment]
Did you actually solved this?

**Comment by CSGrandeur** [comment]
> Did you actually solved this?

"after" a base64 encoded serial number
