### ISSUE TITLE
Missing aggregation statement

### ISSUE THREAD

**Issue by abhushansahu** [graphql-python/graphene-sqlalchemy#262]
Trying to implement a scenario where the graphql produced such as this 
```
query {
alltable (filters: {and: [{a: "condition", {x: "condition1"}}]}, first:10, sort: c_asc){
aggregate(c){
edges{
sum{
node{
d
}}
count{
node{
e}}
}
}}}}
```
will have an equivalent result such as 

`select table.c, sum(table.d), count(table.e) from table where table.a = 'condition' and table.x = 'condition1' order by table.b asc group by table.c limit 10;`

So far I've implemented the https://pypi.org/project/graphene-sqlalchemy-filter/ to generate the filter nodes, but the aggregate/grouping seems afar.

**Comment by erikwrede** [comment]
Maybe `column_property`s (https://docs.sqlalchemy.org/en/14/orm/mapped_sql_expr.html#using-column-property) are a better fit here?
Adding aggregation support to the entire schema is a complex effort, especially with all the different scenarios that could be supported. If you or anyone else seeing this issue sees the need for this library to implement that feature, please open a design discussion in the forum with your proposal! 🙂
