### ISSUE TITLE
Flask example gives error

### ISSUE THREAD

**Issue by cappy123abc** [graphql-python/graphene-sqlalchemy#270]
When I run the flask-sqlalchemy example I get the following error.

Traceback (most recent call last):
  File "./app.py", line 5, in <module>
    from schema import schema
  File "/home/caleb/Development/graphene-sqlalchemy/examples/flask_sqlalchemy/schema.py", line 28, in <module>
    class Query(graphene.ObjectType):
  File "/home/caleb/Development/graphene-sqlalchemy/examples/flask_sqlalchemy/schema.py", line 32, in Query
    all_employees = SQLAlchemyConnectionField(
AttributeError: type object 'Employee' has no attribute 'connection'

**Comment by cappy123abc** [comment]
Whoops, just had to install latest version. Hope this helps someone else.
pip install graphene-sqlalchemy==2.3.0.dev1

**Comment by jnak** [comment]
Sorry about that. The documentation assumes `2.3.0.dev1`. Will release a stable version soon.

**Comment by manuelreis** [comment]
@jnak can we update the documentation so that more people do not face the same issue?

**Comment by jnak** [comment]
@manuelreis Yes I'll work on it this weekend. Sorry for being a bit responsive lately - it's been hard to carve out time for project with everything going on.
