### ISSUE TITLE
type object Employee has no attribute connection

### ISSUE THREAD

**Issue by bjellesma** [graphql-python/graphene-sqlalchemy#272]
Hi,
I'm following the tutorial on https://docs.graphene-python.org/projects/sqlalchemy/en/latest/tutorial/ and I'm receiving the following error when I run my flask app
```
AttributeError: type object 'Employee' has no attribute 'connection'
```
The same will happen for the department object.

I'm using pipenv
```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
flask = "*"
flask-socketio = "*"
flask-graphql = "*"
graphene-sqlalchemy = "*"
sqlalchemy = "*"

[requires]
python_version = "3.7"
```

**Comment by anshajk** [comment]
I was facing this issue but I managed to fix it by upgrading to 2.3.0
