### ISSUE TITLE
Possible to change which model field is used for global id?

### ISSUE THREAD

**Issue by cahna** [graphql-python/graphene-sqlalchemy#275]
I am working with a set of models that use BigInteger primary keys internally, but UUID's externally. 

```python
class Thing(db.Model):
    id = db.BigInteger(primary_key=True, autoincrement=True)
    public_id = db.Column(postgresql.UUID, unique=True, index=True, default=uuid.uuid4)
    name = db.String(nullable=False)

class ThingType(SQLAlchemyObjectType):
    class Meta:
        model = Thing
        interfaces = (Node,)
        exclude_fields = ('id',) # <- Desired
```

Clients should only receive and request resources by their `public_id` values. Internally, however, the `id` field is used for joins. 

 Is it possible to support this scenario with `graphene-sqlalchemy`, or should I use `graphene` by itself to have more control over customization like this?

Example of desired query structure:
```
query {
  thing(id: "86c6735b-1042-4405-8b54-addb84da278a") {
    name
  }
}
```

**Comment by cahna** [comment]
**Update**: I got something working, but it seems that parts of `graphene-sqlalchemy` do not work as expected.

## Working example

![working](https://user-images.githubusercontent.com/1045603/81484749-0089b680-91fd-11ea-90a4-67db7d080902.png)

I was able to achieve the desired behavior using the following code (sections commented as `REQUIRED` must be included or it will not work as expected):
  ```python
  """
  models.py
  """
  import uuid
  from datetime import datetime
  from flask_sqlalchemy import SQLAlchemy


  db = SQLAlchemy()
  PK_TYPE = db.BigInteger().with_variant(db.Integer, "sqlite")


  class GUID(db.TypeDecorator):
      """Platform-independent GUID type.
      Uses PostgreSQL's UUID type, otherwise uses
      CHAR(32), storing as stringified hex values.
      """
      impl = db.CHAR
      # ommitting rest of class code...


  class User(db.Model):
      __tablename__ = 'users'

      id = db.Column(PK_TYPE, primary_key=True, autoincrement=True)
      # unique_id is used as public-facing ID
      unique_id = db.Column(GUID(),
                            nullable=False,
                            unique=True,
                            default=uuid.uuid4)
      username = db.Column(db.String(32),
                           index=True,
                           unique=True,
                           nullable=False)
      hashed_pw = db.Column(db.String(128), nullable=False)
      date_created = db.Column(db.DateTime, default=datetime.utcnow)
      teams = db.relationship('Team', secondary='team_membership')


  class Team(db.Model):
      id = db.Column(PK_TYPE, primary_key=True, autoincrement=True)
      name = db.Column(db.String(32),
                       index=True,
                       unique=True,
                       nullable=False)
      # slug is used as the public-facing ID
      slug = db.Column(db.String(64),
                       index=True,
                       unique=True,
                       nullable=False)
      owner_id = db.Column(PK_TYPE, db.ForeignKey('users.id'))
      owner = db.relationship('User')
      members = db.relationship('User', secondary='team_membership')
  ```

  ```python
  """
  types.py
  """
  import graphene
  from graphene_sqlalchemy import SQLAlchemyObjectType
  from graphene_sqlalchemy.converter import convert_sqlalchemy_type
  from .models import User, Team, GUID


  @convert_sqlalchemy_type.register(GUID)
  def convert_column_to_string(type, column, registry=None):
      return graphene.String


  class UserType(SQLAlchemyObjectType):
      class Meta:
          model = User
          interfaces = (graphene.relay.Node,)
          exclude = ('hashed_pw',)

      id = graphene.ID(required=True)  # REQUIRED
      unique_id = id  # REQUIRED

      @staticmethod
      def resolve_id(parent, info):  # REQUIRED
          return parent.unique_id


  class TeamType(SQLAlchemyObjectType):
      class Meta:
          model = Team
          interfaces = (graphene.relay.Node,)
 
      id = graphene.ID(required=True)  # REQUIRED

      @staticmethod
      def resolve_id(parent, info):  # REQUIRED
          return parent.slug
  ```

### Problems with working example

Because I have lots of models that use the same `id` and `unique_id` pattern, I tried to share the custom id code as an interface. This **did not work**:
    
```python
class GuidNode(graphene.relay.Node):
    id = graphene.ID(required=True)
    unique_id = id

    @staticmethod
    def resolve_id(parent, info):
        return parent.unique_id


class UserType(SQLAlchemyObjectType):
    class Meta:
        model = User
        interfaces = (GuidNode,)
        exclude = ('hashed_pw',)
```
    
![failed-subclass](https://user-images.githubusercontent.com/1045603/81484668-4c882b80-91fc-11ea-9262-896e140b2513.png)

However, creating a `BaseType` that subclasses `SQLAlchemtObjectType` with `Meta.abstract = True` **works**:

```python
class BaseType(SQLAlchemyObjectType):
    class Meta:
        abstract = True

    id = graphene.ID(required=True)
    unique_id = id

    @staticmethod
    def resolve_id(parent, info):
        return parent.unique_id


class UserType(BaseType):
    class Meta:
        model = User
        interfaces = (graphene.relay.Node,)
        exclude = ('hashed_pw',)
```

## Failed attempts
- From the [source for `ORMField`](https://github.com/graphql-python/graphene-sqlalchemy/blob/421f8e48d169a91e20328108c6f56ae0987d21b8/graphene_sqlalchemy/types.py#L52), I thought it may be possible to override the `id` by setting `id = ORMField(type=graphene.ID, model_attr='unique_id', required=True)` on my type. This did not work as expected and I was given an error about unknown kwarg for `model_attr`.

- From the [source for `SQLAlchemyObjectType`](https://github.com/graphql-python/graphene-sqlalchemy/blob/421f8e48d169a91e20328108c6f56ae0987d21b8/graphene_sqlalchemy/types.py#L270), it seemed that I may be able to override which field is used as the id. From my attempts, it seems that this value has no effect.

**Comment by chrisberks** [comment]
Your globally unique identifier should be able to identify a resource across
your entire database, not just a single table. By default, Graphene does this
by combining the GraphQL type name and database primary key, separated by a
colon, then base64 encoding the resulting string.

Base64 encoding and decoding in the console for demonstration:

Encode:
```console
$ echo -n "User:01234" | base64
VXNlcjowMTIzNA==
```

Decode:
```console
$ echo "VXNlcjowMTIzNA==" | base64 --decode
User:01234
```

This will make your `id`s compatable with the `Node` interface. You can now fetch
any object by simply querying the `node` field on the root query object. This is
detailed in the [GraphQL Global Object Identification Specification](https://relay.dev/graphql/objectidentification.htm).

See also: [Global Object Identification](https://graphql.org/learn/global-object-identification/)

There's a great artical that explains this concept on dev.to: [The magic of the Node interface](https://dev.to/zth/the-magic-of-the-node-interface-4le1)

Query:
```graphql
query {
  node(id: "VXNlcjowMTIzNA==") {
    id
    ... on User {
      username
    }
    ... on Team {
      slug
    }
  }
}
```

Result:
```graphql
{
  "data": {
    "node": {
      "cahna"
    }
  }
}
```

You'll need to use the `get_node` and `resolve_id` methods to make this work.

If you'd also like to expose the underlining database primary key, you can
add a `database_id` field and resolver.

I've used a mixin below. You could then use this on the types that use your `global_id` pattern.

```python
from graphene import UUID, relay
from graphene_sqlalchemy import SQLAlchemyObjectType

from .model import Team as TeamModel, User as UserModel


class PublicIDMixin:
    database_id = UUID()

    @classmethod
    def get_node(cls, info, id):
        return (
            cls.get_query(info)
            .filter(cls._meta.model.public_id == id)
            .first()
        )

    @staticmethod
    def resolve_database_id(parent, info):
        return parent.public_id

    def resolve_id(self, info):
        return self.public_id


class User(PublicIDMixin, SQLAlchemyObjectType):
    class Meta:
        model = UserModel
        interfaces = (relay.Node,)
        exclude = ('hashed_pw',)


class Team(SQLAlchemyObjectType):
    class Meta:
        model = TeamModel
        interfaces = (relay.Node,)
```

Hope this helps.

**Comment by cahna** [comment]
Thank you! I appreciate the explanation, examples, and further reading. This has worked for my use case.
