### ISSUE TITLE
Filtering by JSONString

### ISSUE THREAD

**Issue by mogmog** [graphql-python/graphene-sqlalchemy#28]
Hacking around with the example, I have been able to add a JSONB field to the employee class (Replacing SQLite with Postgres 9.6).

Is it possible (or on the road map) to specify a json filter, eg the equivalant in postgres of 'SELECT * from Employee where employee.data ->>'thing' = 'blah', so maybe a schema resembling

````{
  allEmployees {
    edges {
      node {
        name
        data(thing: blah)
    }
  }
}
}
````

**Comment by erikwrede** [comment]
This issue has been inactive for a long time, so I'm closing it.
Filtering is currently unsupported in graphene-sqlalchemy. For 2.x you can use the `graphene-sqlalchemy-filter` library. However, I'm not sure if it natively supports JSON though. We are currently working on more advanced filtering for graphene-sqlalchemy 3.0.

See https://github.com/graphql-python/graphene-sqlalchemy/issues/335 for progress.
