### ISSUE TITLE
Question — Is it possible order results according to a function of the input query?

### ISSUE THREAD

**Issue by cglacet** [graphql-python/graphene-sqlalchemy#283]
I've posted the same question on [Stackoverflow](https://stackoverflow.com/q/63249166/1720199), but I though this might be related to your concerns. 

Here some selected content from this question: 

---

I'm using graphene with sqlalchemy and I have an output object that contains a computed field. The field is computed according to some input query parameters. To simplify, lets consider the computation of a function *f(x)=ax+b* where *a* and *b* are both columns in my `Thing` table and `x` is a variable (grahpql query parameter):

```python
import models

class Thing(SQLAlchemyObjectType):
    class Meta:
        model = models.Thing
        interfaces = (relay.Node, )

    f = graphene.Field(graphene.Float)

    def resolve_f(self, info):
        return self.a * info.context['x'] + self.b
```

In my query I have the following and I would like to sort fields according to the output of the function `f`: 

```python
class Query(graphene.ObjectType):
    best_points = graphene.List(lambda: Thing, x = graphene.Float())

    def resolve_best_points(self, info, x):
        query = Thing.get_query(info)
        return query.all()
```

Is there a way to achieve this in a clean way? Adding some option in `Thing`? Or maybe obtaining the output values within the resolver and then sorting? Or something a bit uglier like adding a middleware to sort outputs from `resolve_best_points`?

  [1]: https://stackoverflow.com/questions/16966163/sqlalchemy-order-by-calculated-column

**Comment by chrisberks** [comment]
You can use SQLAlchemy's `orm.with_expression` and `orm.query_expression` functions to apply ad-hoc expressions to your query, then use them in the `ORDER_BY` clause.

Add a `query_expression` attribute to your `Thing` model.
``` python
# models.py
from sqlalchemy import Float, Integer, orm

class Thing(Base):
    __tablename__ = 'things'
    id = Column(Integer, primary_key=True)
    a = Column(Float)
    b = Column(Float)

    expr = orm.query_expression()
```

You can now use `with_expression` to pass arbitrary SQL expressions to your queries. The value of the `expr` attribute, on `Thing` objects, will be the result of the expression.

``` python
# schema.py
import graphene

from graphene import relay
from sqlalchemy.orm import with_expression

from models import Thing as ThingModel


class Thing(SQLAlchemyObjectType):
    class Meta:
        model = ThingModel
        interfaces = (relay.Node,)


class Query(graphene.ObjectType)
    best_points = graphene.List(Thing, x=graphene.Float())

    def resolve_best_points(self, info, x):
        expr = ThingModel.a * x + ThingModel.b

        return (
            Thing.get_query(info)
            .options(with_expression(ThingModel.expr, expr))
            .order_by(expr)
            .all()
        )
```

More details and a list of caveats to be aware of are in this section of the SQLAlchemy docs: [Query-time SQL expressions as mapped attributes](https://docs.sqlalchemy.org/en/13/orm/mapped_sql_expr.html#query-time-sql-expressions-as-mapped-attributes).
