### ISSUE TITLE
2D Array throws an error on GET

### ISSUE THREAD

**Issue by jbeard4** [graphql-python/graphene-sqlalchemy#288]
Hello,

I have found that a column declaration like this:

```
db.Column(db.ARRAY(db.Float))
```

Which contains a 2D array (as is supported in, for example, Postgresql), yields an error on get:

```
  "message": "float() argument must be a string or a number, not 'list'"
```

Are 2D arrays supported by graphene-sqlalchemy?

Thank you for your help with this.

**Comment by jbeard4** [comment]
I think the issue is here: https://github.com/graphql-python/graphene-sqlalchemy/blob/master/graphene_sqlalchemy/converter.py#L241

The SQLAlchemy dimensions property should be checked: https://docs-sqlalchemy.readthedocs.io/ko/latest/core/type_basics.html#sqlalchemy.types.ARRAY.params.dimensions

I would be happy to contribute this fix. Would you accept a patch for this?

Thank you for your time and attention to this issue.

**Comment by wkevwang** [comment]
Facing this as well. Merging into the main repo would be really helpful!

**Comment by jbeard4** [comment]
@wkevwang This project is not maintained. I recommend using [PostGraphile](https://www.graphile.org/postgraphile/) instead.

**Comment by cglacet** [comment]
Seems like its still an issue today. 

I used @jbeard4 patch and it works as expected. 

```python
from sqlalchemy import types
from graphene import List
from graphene_sqlalchemy import converter
from sqlalchemy.dialects import postgresql

def init_array_list_recursive(inner_type, n):
    return inner_type if n == 0 else List(init_array_list_recursive(inner_type, n-1))

@converter.convert_sqlalchemy_type.register(types.ARRAY)
@converter.convert_sqlalchemy_type.register(postgresql.ARRAY)
def convert_array_to_list(_type, column, registry=None):
    inner_type = converter.convert_sqlalchemy_type(column.type.item_type, column)
    return List(init_array_list_recursive(inner_type, (column.type.dimensions or 1) - 1))

converter.convert_array_to_list = convert_array_to_list
```
