### ISSUE TITLE
Can a registered converter be shadowed to use a type other than a `graphene` type?

### ISSUE THREAD

**Issue by this-vidor** [graphql-python/graphene-sqlalchemy#308]
For example, suppose a developer did not want `sqlalchemy.dialects.postgres.HSTORE` to be converted to `graphene.types.json.JSONString`. Is there a correct way to accomplish that?

**Comment by erikwrede** [comment]
The solution is to override the default type converter:
```python
@convert_sqlalchemy_type.register(postgresql.HSTORE)
def convert_json_to_string(type, column, registry=None):
    return your_graphene_scalar
```
This needs to be called before your `SQLAlchemyObjectType`s are initialized.
