### ISSUE TITLE
How to define an Enum Input in mutation?

### ISSUE THREAD

**Issue by shaozi** [graphql-python/graphene-sqlalchemy#312]
In models.py, I defined a python Enum class:

```python
class EmployeeKind(PyEnum):
    contractor = 1
    fulltime = 2
    parttime = 3
```

 and in schema.py, I defined a mutation class:

```python
class UpdateEmployee(graphene.Mutation):
    class Arguments:
        id = graphene.ID(required=True)
        name = graphene.String()
        department_id = graphene.ID()
        role_id = graphene.ID()
        kind = graphene.Enum.from_enum(EmployeeKind)
...
```

But when running the script, it shows an error:

```shell
Traceback (most recent call last):
  File "....../gqlsql/./app.py", line 5, in <module>
    from schema import schema
  File "....../gqlsql/schema.py", line 181, in <module>
    class Mutation(graphene.ObjectType):
  File "....../gqlsql/schema.py", line 183, in Mutation
    update_employee = UpdateEmployee.Field()
  File "....../gqlsql/.venv/lib/python3.9/site-packages/graphene/types/mutation.py", line 139, in Field
    return Field(
  File "....../gqlsql/.venv/lib/python3.9/site-packages/graphene/types/field.py", line 103, in __init__
    self.args = to_arguments(args or OrderedDict(), extra_args)
  File "....../gqlsql/.venv/lib/python3.9/site-packages/graphene/types/argument.py", line 104, in to_arguments
    raise ValueError('Unknown argument "{}".'.format(default_name))
ValueError: Unknown argument "kind".
```

What does this error mean? Why?

**Comment by shaozi** [comment]
I worked around it by converting the Enum to key value pairs, give it a unique name, and using `graphene.Argument()` to wrap it as an input argument:

```python

kind = graphene.Argument(graphene.Enum('UpdateEmployeeKindEnum', 
                                       [(x.upper(), x.name) for x in EmployeeKind]))

```

Not sure if this is the right way, can anyone confirm?

**Comment by chrisberks** [comment]
`graphene.Enum.from_enum(EmployeeKind)` returns a type object which you then need to call.

This:

```py
class EmployeeKindEnum(PyEnum):
    contractor = 1
    fulltime = 2
    parttime = 3

EmployeeKind = graphene.Enum.from_enum(EmployeeKindEnum)
```

is essentially a dynamic form of:

```py
class EmployeeKind(graphene.Enum):
    contractor = 1
    fulltime = 2
    parttime = 3
```

except the first is based on an existing Python Enum.

**Example:**

```py
# models.py
import enum

class EmployeeKind(enum.Enum):
    contractor = 1
    fulltime = 2
    parttime = 3
```

```py
# schema.py
import graphene

from models import EmployeeKind as EmployeeKindEnum

EmployeeKind = graphene.Enum.from_enum(EmployeeKindEnum)

class UpdateEmployee(graphene.Mutation):
    class Arguments:
        id = graphene.ID(required=True)
        name = graphene.String()
        department_id = graphene.ID()
        role_id = graphene.ID()
        kind = EmployeeKind(required=True)
```

**Comment by shaozi** [comment]
Thank you @chrisberks. However, I tried your example and it errored with:

```
AssertionError: Found different types with the same name in the schema: EmployeeKind, EmployeeKind.
```

**Comment by chrisberks** [comment]
Graphene-SQLAlchemy is generating a GraphQL Enum type as it builds the schema from your SQLAlchemy models. You can override this by using `graphene-sqlalchemy.types.ORMField` to tell Graphene-SQLAlchemy to use our `EmployeeKind` enum instead.

```py
# schema.py
from graphene_sqlalchemy.types import ORMField

from models import Employee as EmployeeModel
from models import EmployeeKind as EmployeeKindEnum

EmployeeKind = graphene.Enum.from_enum(EmployeeKindEnum)


class Employee(SQLAlchemyObjectType):
    class Meta:
        model = EmployeeModel
        interfaces = (relay.Node,)

    kind = ORMField(type=EmployeeKind)


class UpdateEmployee(graphene.Mutation):
    class Arguments:
        id = graphene.ID(required=True)
        name = graphene.String()
        department_id = graphene.ID()
        role_id = graphene.ID()
        kind = EmployeeKind(required=True)
```

**Comment by shaozi** [comment]
It compiles without error. However, a new problem occurs:

If I do the following mutation:

```graphql
mutation {
  updateEmployee(id: "RW1wbG95ZWU6MQ==", kind: contractor) {
    ok
    message
    employee {
      id
      kind
    }
  }
}
```

It uses the value of the enum `1` instead of the string value `contractor` to update the database and leads to the error: 

```
"Bad request, (builtins.LookupError) '1' is not among the defined enum values. Enum name: employeekind. Possible values: contractor, fulltime, parttime\n[SQL: UPDATE employee SET kind=%(kind)s WHERE employee.id = %(employee_id)s]\n[parameters: [{'kind': 1, 'employee_id': 1}]]"
```

**Comment by chrisberks** [comment]
The value that's passed to your `UpdateEmployee.mutate` method will be the _value_ of the Python enum member (in this case `1`).

By default, SQLAlchemy persists the enum member _names_ to the database ("contractor", "fulltime", "parttime"), rather than the _values_. We need to pass one of these _strings_ or an `EmployeeKind` member to SQLAlchemy.

To access the enum member by it's value: `EmployeeKind(1)`.

```py
class UpdateEmployee(graphene.Mutation):
    # ...
    def mutate(root, info, kind, **kwargs):
        kind = EmployeeKind(kind)
        # ...
```

An alternative is to have SQLAlchemy persist the values and not the names by using the `values_callable` parameter in your model. Now the value passed to `mutate` will be persistable as a _string_. You'll need to use strings for your enum member values for this to work.

```py
# models.py
class EmployeeKind(enum.Enum):
    CONTRACTOR = "contractor"
    FULLTIME = "fulltime"
    PARTTIME = "parttime"


class Employee(Base):
    id = Column(Integer, primary_key=True)
    kind = Column(Enum(EmployeeKind, values_callable=lambda x: [e.value for e in x]))
    # ...
```

**Comment by shaozi** [comment]
Thank you very much for the detailed explanation and solutions @chrisberks !

**Comment by shaozi** [comment]
But think about it, since SqlAlchemy pass enum member name to the database by default, why graphene pass enum member value by default? Should graphene with ORMField do the same as sqlalchemy? Maybe this can be changed so there are no mis-understanding?

**Comment by chrisberks** [comment]
Thanks @shaozi!

Graphene v3 has [better Enum support](https://github.com/graphql-python/graphene/wiki/v3-release-notes#better-enum-support), resolvers will receive the Enum member directly rather than the value—as you suggest.

Graphene v3 is still in _beta_ though, Graphene-SQLAlchemy is using v2.

**Comment by erikwrede** [comment]
I am closing this issue, since everything seems to be resolved. For using Graphene v3 enums, I recommend using the Graphene-SQLAlchemy v3 beta until v3 is officially released.
