### ISSUE TITLE
Question: How to not using relay pagination?

### ISSUE THREAD

**Issue by shaozi** [graphql-python/graphene-sqlalchemy#314]
Relay pagination is nice, but sometimes, I just want to have a simple list backref. I know it will not exceed more than 10 elements in the list. so pagination just added a layer of extra work and no benefits.

Is there a way to disable relay pagination?

**Comment by richin13** [comment]
yep, you should be able to use a list, like so:

```python

class Ship(graphene.ObjectType):
    names = graphene.List(graphene.String())
```

then query it like:

```graphql
{
    ship(...) { names }
}
```

resulting in:

```json
{
  "data": {"ship": {"names": [item1, item2, ...]}}
}
```

**Comment by shaozi** [comment]
That is great! I did not think of that it could be so easy!

**Comment by shaozi** [comment]
What about many to many relationship?

**Comment by erikwrede** [comment]
@shaozi it should work exactly the same for a many to many relationship, just use a list on the other side of the relationship as well. 
```
class Destination(graphene.ObjectType)
    name = graphene.String()
    ships = graphene.List(Ship)

class Ship(graphene.ObjectType):
    destinations = graphene.List(Destination)
```

for using plain Strings, you would have to create an extra ObjectType.

**Comment by erikwrede** [comment]
I'm closing this issue, since the problem seems to be solved. Feel free to reply again or open another Issue if you experience further problems.
