### ISSUE TITLE
Question: How to access info in building relay.Node and connection 

### ISSUE THREAD

**Issue by shaozi** [graphql-python/graphene-sqlalchemy#315]
It is convenient to just add two lines of code to do get by id and get all queries:

```python
class EmployeeQuery(graphene.ObjectType):
    employee = relay.Node.Field(Employee)
    all_employees = SQLAlchemyConnectionField(Employee.connection, sort=Employee.sort_argument())
```

My question is, how do I enhance/customize the query so I can access the `info` for authorization purpose?

Currently I have to implement my own resolver, but for `all_employees` I lost the relay edges:

```python
class EmployeeQuery(graphene.ObjectType):
    employee = graphene.Field(Employee, id=graphene.ID(required=True))
    def resolve_employee(parent, info, **args):
        id = args.get('id')
        print(f"resolve_employee: {id}, =========== user = {info.context.user}")
        return relay.Node.get_node_from_global_id(info, id, only_type=Employee)


    all_employees = graphene.List(Employee)
    def resolve_all_employees(parent, info, **args):
        print(f"resolve_all_employee: =========== user = {info.context.user}")
        return Employee.get_query(info).all() 
```

Is there a better more "graphene SQLAlchemy" way?

**Comment by chrisberks** [comment]
Use `SQLAlchemyConnectionField` and have your resolver return `None`.

```py
class EmployeeQuery(graphene.ObjectType):
    all_employees = SQLAlchemyConnectionField(
        Employee.connection, sort=Employee.sort_argument()
    )
    
    def resolve_all_employees(parent, info, **args):
        print(f"resolve_all_employee: =========== user = {info.context.user}")
        return None
```

`return None`, `return` and omitting the return statement are equivalent.

**Comment by shaozi** [comment]
awesome! Thank you, it worked like a charm!  Where is this documented?

**Comment by erikwrede** [comment]
I believe this is currently undocumented. Closing this, as documentation is another issue, the original problem seems to be solved. If you have further questions, feel free to open another issue!
