### ISSUE TITLE
Batching dependent on Relay

### ISSUE THREAD

**Issue by carolineclancy0** [graphql-python/graphene-sqlalchemy#325]
Hi! 

We have been experiencing latency with large queries and found that we have several queries that have the N+1 problem. We added `batching = True` to our SQLAlchemyObjectType meta classes, but have not seen a decrease in the number of DB requests.

Is the batching field reliant on relay to work? I see in all of the batching tests `interfaces = (relay.Node,)` is also included in the Meta class.

Thank you!!!

**Comment by erikwrede** [comment]
I would suggest trying out this library, if your SQLAlchemy schema allows for it. It covers more cases than the SQLAlchemy implementation: https://github.com/operator/sqlalchemy_bulk_lazy_loader
