### ISSUE TITLE
Depending on unmaintained library aiodataloader

### ISSUE THREAD

**Issue by sebix** [graphql-python/graphene-sqlalchemy#326]
Unfortunately https://github.com/syrusakbary/aiodataloader looks unmaintained: Necessary fixes are not released, Maintainers do neither respond nor transfer permissions to others.
aiodataloader is "only" used in one place:
https://github.com/graphql-python/graphene-sqlalchemy/blob/d6dd67e388b58247dd4a03c29bf6e625d6e4e230/graphene_sqlalchemy/batching.py#L15
Please check if it's possible to remove this stale dependency or other alternatives.

**Comment by richin13** [comment]
The whole ecosystem can be considered abandoned/unmaintained at this point, sadly.

**Comment by erikwrede** [comment]
@richin13 is there anything we can do about it? Sad to see such a rich ecosystem go unmaintained with even simple fixes not being merged. I saw the call for maintainers on the main graphene repo, but even there only little activity seems visible.

**Comment by Cito** [comment]
@erikwrede @richin13  I don't think the *whole* ecosystem is abandoned, but parts of it are.

I see two core probems:

1. We don't have a coordinater for the whole graphql-python system (anymore). There were some peole who volunteered, but life or job changes got in their ways. So we again need someone to volunteer as new overall coordinator and protagonist of the ecosystem.
2. Some (not all) projects in the ecosystem are abandoned or unmaintained. We need more people who would be willing to act as maintainers and contact persons for one of these projects.

I don't think these problems are unsolvable. We just need a handful of reliable and comitted people who would not just offer help unspecifically, but really take responsibility as coordinator or maintainers. Then we could refloat the boat.

The reason for the sad state is that working as long-time maintainer of a project is a much more boring and thankless task than creating it once.

It would help if companies that are using the libraries would contribute by sponsoring the maintainers or engaging themselves in the long-time maintenance and coordination of the projects.

I you want to take over maintenance of a seemingly anandoned project, this is absolutely possible. First try to contact the authors and current maintainers. If they cannot be reached, you can request a name transfer, as explained [here](https://www.python.org/dev/peps/pep-0541/).

**Comment by richin13** [comment]
@Cito agreed!
I didn't mean to generalize my concerns to all of `graphql-python` but to `graphene` specifically. I know the core libs are heavily maintained (thanks to you!) and actively used in other libraries beyond graphene.

As per your points, those are valid, I'd say we've done it but with no success. Maybe is a matter of pushing harder I don't know. I think people willing to jump in and contribute were slowly pushed away by the lack of interest from the people actually capable of transferring and approving new maintainers.

**Comment by palisadoes** [comment]
@Cito I'm interested in partially sponsoring work on `graphene-sqlalchemy` to integrate filters like `graphene-sqlalchemy-filter`. How should I proceed?

**Comment by erikwrede** [comment]
Seems like the library has a new maintainer, urgent fixes have also been pushed to PyPi:
https://github.com/syrusakbary/aiodataloader/issues/20#issuecomment-1018405467

Closing this issue for now.
