### ISSUE TITLE
Schema creation code broken in Flask-SQLAlchemy website tutorial

### ISSUE THREAD

**Issue by edbaskerville** [graphql-python/graphene-sqlalchemy#34]
# Summary

The schema creation code in the website tutorial does not work. Changing it to match `examples/flask_sqlalchemy` fixes the problem.

# Details

In the [tutorial on the website](http://docs.graphene-python.org/projects/sqlalchemy/en/latest/tutorial/), the code to create the schema looks like this:

```python
schema = graphene.Schema()

class Department(SQLAlchemyObjectType):
    # ...

class Employee(SQLAlchemyObjectType):
    # ...

class Query(graphene.ObjectType):
    node = relay.Node.Field()
    all_employees = SQLAlchemyConnectionField(Employee)

schema.query = Query
```

When the example query is submitted, this results in an error:

```json
{
  "errors": [
    {
      "message": "'NoneType' object has no attribute 'fields'"
    }
  ],
  "data": null
}
```

The code in `examples/flask_sqlalchemy` is different and works; it defines the schema like this:

```python
schema = graphene.Schema(query=Query, types=[Department, Employee, Role])
```

and if you change the website tutorial code to match, the problem goes away:

```python
schema = graphene.Schema(query=Query, types=[Department, Employee])
```

This also works:

```python
schema = graphene.Schema(query=Query)
```

**Comment by jnak** [comment]
Closing this for now since I believe since this is no longer a problem. The documentation has been updated recently.
