### ISSUE TITLE
Remove unused metadata

### ISSUE THREAD

**Issue by n00el** [graphql-python/graphene-sqlalchemy#374]
Is there a way to turn off the pagination?

I don't use it in every query and my GraphQL query becomes really un-readable after every edge-node pair.

For e.g., now:
`
query {
  authors {
    edges {
      node {
        id
        name
        books {
          edges {
            node {
              id
              name
            }
          }
        }
      }
    }
  }
}
`
What i want:
`
query {
  authors {
    id
    name
    books {
        id
        name
      }
    }
}
`

**Comment by MattKleinsmith** [comment]
I also want this. @n00el did you figure out a way to turn it off?

The dream:

![image](https://user-images.githubusercontent.com/8968171/218836485-ec7656a2-d60c-4852-ba2a-bf509e83701e.png)
