### ISSUE TITLE
One method for creating a Union type. Is there a better way?

### ISSUE THREAD

**Issue by dfee** [graphql-python/graphene-sqlalchemy#38]
So after some extreme hacking, I figured out how to create a Union type that I'll share below. I'd like to get some input from the authors if this is a fragile solution, and whether there is a better approach.

Here's what I've done (take special note of this: `StreamEventOT._meta.model = StreamEvent`):
```
import graphene
from graphene import relay
from graphene_sqlalchemy import (
    SQLAlchemyConnectionField,
    SQLAlchemyObjectType,
)
import spark.graphql._prepare

def connection_for_type(_type):
    class Connection(graphene.Connection):
        total_count = graphene.Int()

        class Meta:
            name = '{}Connection'.format(_type._meta.name)
            node = _type

        def resolve_total_count(self, args, context, info):
            return context['session'].query(_type._meta.model).count()

    return Connection

class UserOT(SQLAlchemyObjectType):
    class Meta:
        model = User
        interfaces = (relay.Node,)
UserOT.Connection = connection_for_type(UserOT)


class AlertOT(SQLAlchemyObjectType):
    class Meta:
        model = Alert
        interfaces = (relay.Node,)
AlertOT.Connection = connection_for_type(AlertOT)


class MessageOT(SQLAlchemyObjectType):
    class Meta:
        model = Message
        interfaces = (relay.Node,)
MessageOT.Connection = connection_for_type(MessageOT)


class TaskOT(SQLAlchemyObjectType):
    class Meta:
        model = Task
        interfaces = (relay.Node,)
TaskOT.Connection = connection_for_type(TaskOT)


class StreamEventOT(graphene.Union):
    class Meta:
        types = (AlertOT, MessageOT, TaskOT)

StreamEventOT.Connection = connection_for_type(StreamEventOT)
StreamEventOT._meta.model = StreamEvent

class Query(graphene.ObjectType):
    all_users = SQLAlchemyConnectionField(UserOT)
    all_stream_events = SQLAlchemyConnectionField(StreamEventOT.Connection)
    node = relay.Node.Field()


schema = graphene.Schema(
    query=Query,
    types=[
        UserOT,
        StreamEventOT,
        AlertOT,
        MessageOT,
        TaskOT,
    ]
)
```

[Keywords for anyone searching for polymorphism, or joined table inheritance]

**Comment by dfee** [comment]
This was doubly tough because `graphene.Union` is undocumented, that it can stand in place of a `graphene.ObjectType` on a connection field isn’t readily visible in the codebase or it's tests, and if you supply too many options to a `class Meta` on a Union, `graphene` will barf. You also can’t subclass `Union`, because it’s metaclass determines what options are necessary (or superfluous), and so you have to subclass `UnionMeta`. Then, however, the connection field is unhappy because your custom type isn’t a subclass of Union type (i.e. an exception is raised).

**Comment by dfee** [comment]
I just realized there may be little value to using a SQLAlchemyConnectionField if I could just create a ConnectionField with a custom resolve method.

Perhaps that's the right realization.

**Comment by sebastiandev** [comment]
@dfee Im struggling with this as well, i need to return a paginated result of a query that returns different types. The problem is that SQLAlchemyConnectionField doesnt accept graphene.Union type as input, so im not sure what to do here. I dont like the idea of turning that into a List, did you find a better solution?

**Comment by dfee** [comment]
I never did find a better solution.
