### ISSUE TITLE
Flask example gives ImportError

### ISSUE THREAD

**Issue by MattKleinsmith** [graphql-python/graphene-sqlalchemy#380]
# Might be the only answer for now?

Approach: Downgrade.

How: Replace the _entire_ contents of `graphene-sqlalchemy/examples/flask_sqlalchemy/requirements.txt` with:

```
flask-graphql==2.0.1
graphene==2.1.9
graphene-sqlalchemy==2.3.0
```

# Original post

Hello,

I followed the README instructions for [Example Flask+SQLAlchemy Project](https://github.com/graphql-python/graphene-sqlalchemy/tree/master/examples/flask_sqlalchemy) and I'm getting the following error:

`ImportError: cannot import name 'get_default_backend' from 'graphql' (/home/mwk/code/graphene-sqlalchemy/.venv/lib/python3.9/site-packages/graphql/__init__.py)`

My intention with this issue is to figure it out, documenting it for others, including a future me. Help is welcomed.

Upon `pip install -r requirements.txt`, I see this list of packages and versions (removed some probably-irrelevant ones:

"Successfully installed":

- Flask-GraphQL-2.0.0
- SQLAlchemy-1.4.46
- flask-2.2.2
- graphene-3.2.1
- graphene-sqlalchemy-3.0.0b3
- graphql-core-3.2.3
- graphql-relay-3.2.0
- graphql-server-core-1.1.1

Perhaps one of these versions is not the one I should be using.

I'm using Python 3.9.4, on WSL 2, Ubuntu 22.04.1 LTS, VS Code, pipenv shell.

Relevant discussions:

https://github.com/graphql-python/graphene/issues/1086
https://stackoverflow.com/questions/70204957/flask-graphql-import-fails
https://github.com/graphql-python/graphene-sqlalchemy/issues/348
https://github.com/graphql-python/graphql-server/issues/29
https://github.com/graphql-python/flask-graphql/issues/66

**Comment by MattKleinsmith** [comment]
Going to try downgrading Graphene from v3.0, because [the README](https://github.com/graphql-python/graphene-sqlalchemy) says:

> "Version 3.0 is in beta stage. Please read #348 to learn about progress and changes in upcoming beta releases."

**Comment by MattKleinsmith** [comment]
Okay, flask-graphql's fix was to pin graphql-core to be under version 3.

However, the latest graphene versions require graphql-core to be over version 3.1.

So, I will try to find the latest graphene version that allows graphql-core to be under version 3.

**Comment by MattKleinsmith** [comment]
Seems to be working now:

![image](https://user-images.githubusercontent.com/8968171/218831889-2ce5546f-c2c5-4474-ad4a-b615cdc0772a.png)

Approach: Downgrade.

How: Replace the _entire_ contents of `graphene-sqlalchemy/examples/flask_sqlalchemy/requirements.txt` with:

```
flask-graphql==2.0.1
graphene==2.1.9
graphene-sqlalchemy==2.3.0
```

**Comment by erikwrede** [comment]
I'd strongly advise using the 3.0 beta if you're starting off a new project. It works best together with an `asyncio`-based framework like `FastAPI`, but flask is also fine.
https://github.com/ciscorn/starlette-graphene3

This should work with flask + graphene 3: https://github.com/graphql-python/graphql-server
