### ISSUE TITLE
How to remove "edges" and "node" from query?

### ISSUE THREAD

**Issue by MattKleinsmith** [graphql-python/graphene-sqlalchemy#381]
I would like to be able to use syntax like this:

![image](https://user-images.githubusercontent.com/8968171/218857220-c98c89ca-91b9-4de7-88e0-853a9b3dc6be.png)

But instead I must do something like this:

```
{
    pets {
        edges {
            node {
                name
            }
        }
    }
}
```

Another example:

> For e.g., now:
> query { authors { edges { node { id name books { edges { node { id name } } } } } } }
> What i want:
> query { authors { id name books { id name } } }

From another person wanted the same thing here: https://github.com/graphql-python/graphene-sqlalchemy/issues/374

Will keep poking at examples and the code to try to find a way. Which package is responsible for the edges-node syntax? Is it graphene-sqlalchemy or graphene itself?

**Comment by MattKleinsmith** [comment]
https://github.com/graphql-python/graphene/issues/1073

**Comment by MattKleinsmith** [comment]
Relay wants it:

https://relay.dev/graphql/connections.htm

To conform with pagination best practices:

https://graphql.org/learn/pagination/

**Comment by MattKleinsmith** [comment]
Re-opening because I'd like to know how to turn off pagination, if it's possible. The edge-node syntax makes sense to me for relationships, but I would like to turn it off for basic queries, like getting all product prices.

Instead of this:

```
{
    "data": {
        "allProducts": {
            "edges": [
                {
                    "node": {
                        "price": 39.99
                    }
                },
                {
                    "node": {
                        "price": 49.95
                    }
                }
            ]
        }
    }
}
```

Would prefer:

```
{
    "data": {
        "allProducts": [
                {
                    "price": 39.99
                },
                {
                    "price": 49.95
                }
          ]
    }
}
```

**Comment by MattKleinsmith** [comment]
Re-opening because I'd like to know how to turn off pagination, if it's possible. The edge-node syntax makes sense to me for relationships, but I would like to turn it off for basic queries, like getting all product prices.

Instead of this:

```
{
    "data": {
        "allProducts": {
            "edges": [
                {
                    "node": {
                        "price": 39.99
                    }
                },
                {
                    "node": {
                        "price": 49.95
                    }
                }
            ]
        }
    }
}
```

Would prefer:

```
{
    "data": {
        "allProducts": [
                {
                    "price": 39.99
                },
                {
                    "price": 49.95
                }
          ]
    }
}
```

**Comment by MattKleinsmith** [comment]
Okay, I am learning. This is a feature of Relay.

Here's the mental model that Relay wants:

![image](https://user-images.githubusercontent.com/8968171/218875550-b924e000-3ef2-4c05-84c3-9856a3474970.png)

And here's how they implement it in GraphQL (which doesn't allow properties on edges):

![image](https://user-images.githubusercontent.com/8968171/218875596-8dd5759d-7b40-4467-978c-2147727f87dc.png)

**Comment by MattKleinsmith** [comment]
This diagram clicks even more with the graphene-sqlalchemy behavior I'm seeing:

![image](https://user-images.githubusercontent.com/8968171/218876934-40c44b43-b511-4725-9489-5920f2900999.png)

**Comment by erikwrede** [comment]
Hey Matt, good to see that you've familiarized yourself with the Relay spec 😊  I agree that it is confusing at first, but once you've got the intuition, it makes a lot more sense-
However, I think you've got a point with your statements. Sometimes you don't need all the pagination info but just want to get the benefits of a connection (e.g. filtering or other constraints), but don't need the edges. Currently prototyping an optional `nodes` field on the connections:

```gql
{
    pets {
        nodes {
              name
        }
    }
}
```
This way you can get rid of the additional nesting layer in cases where you really don't need it. Please LMK if you're interested in that, so I can tag you for PR review once it's ready in a few weeks. 🙂 

If you have some specific points of that could be improved on the graphene-sqlalchemy docs, I'd appreciate any PRs bringing improvements.

Cheers

**Comment by MattKleinsmith** [comment]
Hi @erikwrede, thank you for replying. Yes, please tag me in the PR.

**Comment by erikwrede** [comment]
Hi @MattKleinsmith, the first PR is here: https://github.com/graphql-python/graphene/pull/1499
Another PR will be necessary to add native support in `graphene-sqlalchemy`, but this change enables us to work with the native graphene-relay `Connections`. Please LMK what you think :)
