### ISSUE TITLE
Support for sqlalchemy ^2.0.0

### ISSUE THREAD

**Issue by banool** [graphql-python/graphene-sqlalchemy#393]
Hey, I've searched through all the open / closed issues I could find but couldn't see anything for this issue. I'm trying to use sqlalchemy and I see that even the latest pre-release version (3.0.0b4) has this version requirement: `>=1.1,<2`. Are there any plans to support sqlalchemy 2+?

**Comment by erikwrede** [comment]
Hey there, I just merged the relevant PR into master. Itll be included in the next release 😊

**Comment by banool** [comment]
Awesome thanks!!

**Comment by davis-ust** [comment]
Hi, I was just curious. When can I expect the next release? And thanks for your contributions.

**Comment by erikwrede** [comment]
@davis-ust since we're still in beta I want to group the beta releases to ensure we put out meaningful work packets. Roughly expect a few weeks max, as we finish up some other tasks.

**Comment by dmorris-prologis** [comment]
That good news. Thanks @erikwrede

**Comment by forana** [comment]
@erikwrede any word on when that v5 beta is coming?
