### ISSUE TITLE
Order by option is missing

### ISSUE THREAD

**Issue by honify** [graphql-python/graphene-sqlalchemy#40]
Great job,
Order by option is missing.

**Comment by Cito** [comment]
When trying to create something reusable I came up with this idea for creating "order by" options automatically:
```python
    def sort_enum_for(cls):
        """Create Graphene Enum for sorting a SQLAlchemy class query"""
        name = cls.__name__ + 'SortEnum'
        items = []
        for attr in inspect(cls).attrs:
            key = attr.key.upper()
            expr = attr.expression
            items.extend([
                (key + '_ASC', expr), (key + '_DESC', expr.desc())])
        return graphene.Enum(name, items)
```
Assuming you have this SQLAlachemy object type:
```python
    class UserType(SQLAlchemyObjectType):
        class Meta:
            model = User
```
You could then define the following query:
```python
    users = List(UserType, sort=Argument(List(sort_enum_for(User))))
```
This will give you all the options for sorting user queries in any way you like, with multiple columns and options for descending order. A query could look like this:
```graphql
    query{
      users(sort: [LAST_NAME_ASC, FIRST_NAME_ASC, ID_DESC]) {
          id
          firstName
          lastName
      }
    }
```
The resolver would be very simple:
```python
    def resolve_users(self, info, sort):
        query = UserType.get_query(info)
        return query.order_by(*sort)
```
I think this is a pretty clever solution that results in very intuitive and readable code. If others agree that this should go into graphene_sqlalchemy, I can create a pull request with tests.

**Comment by Cito** [comment]
One point to discuss is whether `sort_enum_for()` should take the SQLALchemy base class or the Graphene SQLAlchemy Object Type as argument, or whether both should be allowed. Passing the Graphene has the advantage that the name of the enum type could be derived from the Graphene object type name which might be different from the SQLAlchemy base class name.

**Comment by CaselIT** [comment]
I think that a default order should be added, especially when using relay to get a list of edges since [sql does not guarantee an order if no `order by` is specified](https://dba.stackexchange.com/questions/6051/what-is-the-default-order-of-records-for-a-select-statement-in-mysql)

A relay query `elements(first: 2 after: ...){edges{ node{ ... } } }`
will produce a statement like `SELECT ... FROM <table> LIMIT 2 OFFSET <the offset>`
but since no `order by` clause is used the returned rows can be arbitrary ones

**Comment by Cito** [comment]
@CaselIT You can always do that, returning something like `query.order_by(*sort or [UserType.id])`. You can also define a default orderding in GraphQL with `sort=Argument(..., default_argument=[...])`. In some cases you might not want to do that, like when in some cases you sort on the client anyway. Adding the default "order by" on the server would then only cause an unnecessary delay.

**Comment by CaselIT** [comment]
I'm not sure how can I return `query.order_by(*sort or [UserType.id])` when using relay with an `SQLAlchemyConnectionField`
As an example, in the situation below
```py
class User(Base):
  id = sa.Column(sa.Integer)
  name = sa.Column(sa.Text)

class UserType(SQLAlchemyObjectType):
  class Meta:
    model = User

class UserQuery(ObjectType):
  users = SQLAlchemyConnectionField(UserType)
```

Even if I define a `resolver_users` method in `UserQuery` it will not be used to get the list of Users
@Cito Do you have any advice other than subclass `SQLAlchemyConnectionField` so support ordering?

**Comment by Cito** [comment]
@CaselIT Right, since `SQLAlchemyConnectionField` comes with its own resolver that does not care about ordering, you would need to subclass it to make it sortable. But that's very easy:
```python
from graphene_sqlalchemy.utils import get_query

class SortableSQLAlchemyConnectionField(SQLAlchemyConnectionField):

    @classmethod
    def get_query(cls, model, info, sort=None, **args):
       return get_query(model, info.context).order_by(*sort or [model.id])
```
You can then use this field in a similar way:
```python
    users = SortableSQLAlchemyConnectionField(UserType,
      sort=Argument(List(sort_enum_for(User))))
```
Btw, you also need to add `interfaces = (relay.Node,)` ot the `Meta` class of  `UserType`.

Might be a good idea to add this kind of sortability to the `SQLAlchemyConnectionField` by default.

**Comment by CaselIT** [comment]
thanks @Cito I thought I would need to to something similar
> Btw, you also need to add interfaces = (relay.Node,) ot the Meta class of UserType.

yes I forgot in the example

> Might be a good idea to add this kind of sortability to the SQLAlchemyConnectionField by default.

If I have time to implement something I'll add a PR

**Comment by Cito** [comment]
The SQLAlchemyConnectionField should then also have the sort Argument added by default.

**Comment by najens** [comment]
Hi am trying to implement this but get the error "name Argument is not defined" for the following code sort=Argument(List(sort_enum_for(User)))). Where does the 'Argument' function or class come from? Is this something I have to import or define myself?

**Comment by marvinkome** [comment]
This doesn't work for nested fields e.g 
```
query publicUser($name: String){
	publicUser(name: $name){
    uuid
    posts(sort: title_asc){
      edges{
        node{
          title
        }
      }
    }
  }
}
```
