### ISSUE TITLE
Support for python 3.12

### ISSUE THREAD

**Issue by richin13** [graphql-python/graphene-sqlalchemy#416]
From the `pkg_resources` docs: [setuptools.pypa.io/en/latest/pkg_resources.html](https://setuptools.pypa.io/en/latest/pkg_resources.html)

> Use of pkg_resources is deprecated in favor of [importlib.resources](https://docs.python.org/3.11/library/importlib.resources.html#module-importlib.resources), [importlib.metadata](https://docs.python.org/3.11/library/importlib.metadata.html#module-importlib.metadata) and their backports ([importlib_resources](https://pypi.org/project/importlib_resources), [importlib_metadata](https://pypi.org/project/importlib_metadata)). Some useful APIs are also provided by [packaging](https://pypi.org/project/packaging) (e.g. requirements and version parsing). Users should refrain from new usage of pkg_resources and should work to port to importlib-based solutions.

Python 3.12 has removed `pkg_resources` from the standard library: [docs.python.org/3/whatsnew/3.12.html](https://docs.python.org/3/whatsnew/3.12.html) and this project makes use of it in the `graphene_sqlalchemy/utils.py` file:

https://github.com/graphql-python/graphene-sqlalchemy/blob/eb9c663cc0e314987397626573e3d2f940bea138/graphene_sqlalchemy/utils.py#L8

https://github.com/graphql-python/graphene-sqlalchemy/blob/eb9c663cc0e314987397626573e3d2f940bea138/graphene_sqlalchemy/utils.py#L23-L34

**Comment by erikwrede** [comment]
Adding 3.12&3.13 support was still on my list for this library, thanks for the PR, will check it out this week!

**Comment by richin13** [comment]
@erikwrede thank you! looks like we'd need to drop support for 3.7 (which has reached EOL anyways). Could also drop 3.8 which is also EOL.

Any thoughts?

**Comment by erikwrede** [comment]
@richin13 sounds good to also drop 3.8, but I'd prefer doing that together with adding 3.13

**Comment by richin13** [comment]
> @richin13 sounds good to also drop 3.8, but I'd prefer doing that together with adding 3.13

@erikwrede  good call, I've updated the PR accordingly.

As a side note, we should seriously consider upgrading dev dependencies here (adding a proper package manager, dropping SQLAchemy 1.2 and upgrading tox, to mention some)

**Comment by erikwrede** [comment]
@richin13 also on the list. Sadly my time budget for open source (and also that of the other people with access on this project) has been a little tight this year. The idea was to switch Graphene & -sqlalchemy to Poetry

**Comment by richin13** [comment]
@erikwrede gotchu! how's your time for PR reviews? I can help pushing the code updates if there's support/time to review the PRs

**Comment by Robert-van-Barlingen** [comment]
+1

**Comment by flash42** [comment]
It would be super nice if you could merge the fix 🙏

**Comment by erikwrede** [comment]
@richin13 there is time for reviews.Apart from me, you can also ping @jendrikjoe @sabard @PaulSchweizer for reviews, as we all have write access. Best to just use a list, but usually its fastest to ping me. Another option is to DM me on the Graphene Discord.

Thanks again, please keep the contribs coming!

**Comment by erikwrede** [comment]
3.0.0rc2 😊
