### ISSUE TITLE
filter how to use？

### ISSUE THREAD

**Issue by fangaofeng** [graphql-python/graphene-sqlalchemy#42]
My ui have a search , how can i use relay?
how do i   realize this example by connectfiled or relay?
```
query combineMovies {
  allMovies(filter: {
    OR: [{
      AND: [{
        releaseDate_gte: "2009"
      }, {
        title_starts_with: "The Dark Knight"
      }]
    }, {
      title: "Inception"
    }]
  }) {
    title
    releaseDate
  }
}

result:
{
  "data": {
    "allMovies": [
      {
        "title": "Inception",
        "releaseDate": "2010-08-28T20:00:00.000Z"
      },
      {
        "title": "The Dark Knight Rises",
        "releaseDate": "2012-07-20T00:00:00.000Z"
      }
    ]
  }
}
```

**Comment by mrkaspa** [comment]
Same problem here

**Comment by BenjamWhite** [comment]
same!

**Comment by shanmugh** [comment]
+1

**Comment by erikwrede** [comment]
This issue has been inactive for a long time, so I'm closing it.
Filtering is currently unsupported in graphene-sqlalchemy. For 2.x you can use the `graphene-sqlalchemy-filter` library. We are currently working on more advanced filtering for graphene-sqlalchemy 3.0. 

See #335 for progress.
