### ISSUE TITLE
Support for Custom Column Types?

### ISSUE THREAD

**Issue by mekhami** [graphql-python/graphene-sqlalchemy#53]
I don't see anything in the documentation and a brief look through the source code didn't reveal anything immediately. I have a custom GUID type (as documented in the sqlalchemy docs here: http://docs.sqlalchemy.org/en/latest/core/custom_types.html#backend-agnostic-guid-type) and when I try to use the SQLAlchemyObjectType with the model metaclass, it doesn't know how to convert type GUID. Is there a way to handle these custom column types? Do I need to just subclass SQLAlchemyObjectType and make it understand what that is?

Thanks for any help.

**Comment by mekhami** [comment]
Ah, I can register them the same way the converters are registered in converter.py

Sorry for the bother!

**Comment by rodneykeeling** [comment]
Can you explain how you did this? Did you just modify the source, or was there a better way of adding another type?

**Comment by jcooz** [comment]
I just ran into this same issue as well.  We have several custom subclasses of `TypeDecorator` from `sqlalchemy.types`

Currently the solution is to modify `graphene_sqlalchemy/converter.py`

Importing out custom types decorating the `convert_column_to_string` method like so:
`@convert_sqlalchemy_type.register(GUID)`

I'd love to know of a better solution without modifying graphene_sqlalchemy.

**Comment by mekhami** [comment]
You don't have to use the `convert_sqlalhemy_type.register` function in `graphene_sqlalchemy/converter.py`. You can use it anywhere! So wherever you declare your schema, you can do this:

```
from my_custom_types import GUID

@convert_sqlalchemy_type.register(GUID)
def convert_column_to_string(type, column, registry=None):
    return String(description=get_column_doc(column),
                  required=not(is_column_nullable(column)))
```

Whenever your schema is imported and run, the conversion will also be registered.

**Comment by jcooz** [comment]
Awesome thanks for the tip.  This allowed me to move the decorators and leave the module unmodified.  Thanks!
