### ISSUE TITLE
How to have edges/totalCount on a relationship field?

### ISSUE THREAD

**Issue by rok-povsic** [graphql-python/graphene-sqlalchemy#58]
Hey,

I'd like to have *edges/node/totalCount* support on a relationship field. 

E.g. if looking at the flask_alchemy example app, I'd like to have query such as this (changes are in bold):

<pre>
{
  allEmployees {
    edges {
      node {
        id,
        name,
        department {
          <b>totalCount</b>
          <b>edges {</b>
              id,
              name
           <b>}</b>
        },
        role {
          <b>totalCount</b>
          <b>edges {</b>
            id,
            name
           <b>}</b>
        }
      }
    }
  }
}
</pre>

Can this be done?

Thank you

**Comment by shanmugh** [comment]
+1

**Comment by shanmugh** [comment]
Also, I tried the work-around suggested here - https://github.com/graphql-python/graphene/issues/151 by using https://pypi.python.org/pypi/graphene-sqlalchemy/2.0.dev2017072601 but the `Connection` object appears to be missing the `length` field. 

I had to fork from graphene-sqlalchemy-1.1.1 and add this patch (https://github.com/graphql-python/graphene-sqlalchemy/pull/36/commits/d66aa074a6606be0f359f95f55903c3a3560acd8) to get it working.

**Comment by singingwolfboy** [comment]
@shanmugh, can you make a pull request to add your modification to graphene-sqlalchemy? Or post a working example, so that someone else can do so? I'd be happy to make that pull request for you, if you'd like.

**Comment by neriusmika** [comment]
@singingwolfboy, that modification (length) is already added, but if you need totalCount in your connection, you must inherit Connection class. Because totalCount is not in relay specification and not everyone needs it.

**Comment by singingwolfboy** [comment]
@neriusmika Can you show me how to do that? This is the code I have so far, and it doesn't seem to work...

```python
import graphene
from graphene.relay import Node
from graphene_sqlalchemy import SQLAlchemyObjectType, SQLAlchemyConnectionField
from myapp import models


class CountableConnection(SQLAlchemyConnectionField):
    total_count = graphene.Int()

    def resolve_total_count(self, info):
        return self.length


class Contact(SQLAlchemyObjectType, interfaces=[Node]):
    class Meta:
        model = models.Contact


class User(SQLAlchemyObjectType, interfaces=[Node]):
    class Meta:
        model = models.User
        
    contacts = CountableConnection(Contact)
```

**Comment by neriusmika** [comment]
You need to inherit CountableConnection from graphene.relay.Connection, not from SQLAlchemyConnectionField. But there is a problem to pass that connection to your Contact class. It has connection parameter, but now it's useless, because Connection class needs node parameter and you will have circular reference. Probably the simplest way would be to reassign graphene.relay.Connection (look at https://github.com/graphql-python/graphene-sqlalchemy/issues/65#issuecomment-328722674), but then it will be used in all your connections. The other way (which I prefer) is to change SQLAlchemyObjectType implementation.

**Comment by singingwolfboy** [comment]
@neriusmika That's helpful, but do you think you could provide an actual code example? I find it's easier to refer to an example, and tweak it from there.

**Comment by neriusmika** [comment]
Based on your example, you can try this code, but I did not check it:

```python
import graphene
from graphene.relay import Node
from graphene_sqlalchemy import SQLAlchemyObjectType, SQLAlchemyConnectionField
from myapp import models


class CountableConnection(graphene.relay.Connection):
    class Meta:
        abstract = True

    total_count = graphene.Int()

    @staticmethod
    def resolve_total_count(root, info):
        return root.length

graphene.relay.Connection = CountableConnection


class Contact(SQLAlchemyObjectType, interfaces=[Node]):
    class Meta:
        model = models.Contact


class User(SQLAlchemyObjectType, interfaces=[Node]):
    class Meta:
        model = models.User
        

class Query(graphene.ObjectType):
    node = Node.Field()

    all_users = SQLAlchemyConnectionField(User)
```

**Comment by singingwolfboy** [comment]
That seems to work. Thank you for the help!

**Comment by sebastiandev** [comment]
Im looking for the same, but this approach is not working for me. 
The relay.Connection is not been replaced, is still the base Connection. How can I specify that I want to use another Connection class?

I see SQLAlchemyObjectType creates one automatically (which we override with CountableConnection should be that one, but is still using the base one), and you can also specify a connection instance, but the connection requires a node, so not sure how I could create it or where exactly in the code should the connection be defined.

Thanks

**Comment by CaselIT** [comment]
I've added a PR to fix this issue here https://github.com/graphql-python/graphene-sqlalchemy/pull/104

**Comment by docelic** [comment]
Here is a working example which uses the foundation present in `graphene-sqlalchemy`, and which does not modify `graphene.relay.Connection` globally:

New subclass which will add `totalCount` field to connections which use it:
```
class GCountedConnection(graphene.relay.Connection):
  class Meta:
    abstract = True

  total_count = graphene.Field(graphene.NonNull(graphene.Int))
  def resolve_total_count(s,i, **kwargs):
    return(s.length)
```

And model's GraphQL definition:
```
class GModelA(graphene_sqlalchemy.SQLAlchemyObjectType):
  class Meta:
    model = ModelA
    interfaces = (graphene.relay.Node, )
    connection_class = GCountedConnection
```

When `graphene-sqlalchemy` finds a relation pointing to ModelAs, it will turn it into a connection as usual, but using this custom connection class. (E.g. if you have ModelB with field "model_as = db.relationship('ModelA', secondary=...)", then querying its `modelAs` will return a counted connection).

And if you want to retrieve ModelAs from the root of the tree, then either define "model_as" on the root object (if you have a meaningful one), or manually define the field and provide its resolver, e.g.:

```
class GRoot(graphene.ObjectType):

  model_as = SQLAlchemyConnectionField(GModelA)
  def resolve_model_as(s,i):
    query = GModelA.get_query(i)
    return(query)

schema = graphene.Schema(
  query=Groot,
  auto_camelcase=True,
)
```

**Comment by gu3sss** [comment]
I have been trying the above suggestion and struggling to succeed. Constantly getting the below,
`Cannot query field \"totalCount\" on type \"TestConnection`

**Comment by AlexEshoo** [comment]
I had the same requirement to add a `totalCount` and `edgeCount` to the connection object, but also I needed to add a convenience field called `nodes` to the top level of the connection to return the edges without cursors and deep nesting. I ended up achieving it by sub-classing `SQLAlchemyConnectionField`:

```python
class ExtendedSQLAlchemyConnectionField(SQLAlchemyConnectionField):
    @property
    def type(self):
        connection_type = super().type
        node_type = connection_type._meta.node  # !!!!

        # We have to define the class at run time in a closure to access the specific `node_type` class
        # of the ConnectionField to be able to supply the convenience field `nodes` at the top level of
        # the connection object.
        class ExtendedConnection(relay.Connection):
            class Meta:
                node = node_type

            total_count = graphene.Int()
            edge_count = graphene.Int()
            nodes = graphene.List(node_type)  # Inject the specific `node` class Field Type

            @staticmethod
            def resolve_total_count(root, info):
                return root.length

            @staticmethod
            def resolve_edge_count(root, info):
                return len(root.edges)

            @staticmethod
            def resolve_nodes(root, info):
                return [edge.node for edge in root.edges]

        return ExtendedConnection
```

This lets me define my types in the normal way:

```python
class Dog(SQLAlchemyObjectType):
    class Meta:
        model = DogModel
        interfaces = (relay.Node,)
```

and run queries like:

```gql
query {
    allDogs {
        totalCount
        edgeCount
        nodes {
            id
        }
        edges {
            cursor
            node {
                id
            }
        }
    }
}
```

Not sure if this is the best approach, but it works and if it saves someone else from trying to understand the inner workings of graphene, I'm glad to share it.

**Comment by gu3sss** [comment]
@AlexEshoo Thanks a lot sharing. I was able to finally able to get it to working this morning. Nonetheless, it seems like the value of total count I get is actually before Graphql does a DISTINCT on the resultset. To be clear, if my query fetched 50 matching records from my db and only 20 are unique, I see 50 in total count but only get 20 unique records in result.

**Comment by avbentem** [comment]
@AlexEshoo,

> I ended up achieving it by sub-classing `SQLAlchemyConnectionField`
> ...
> This lets me define my types in the normal way:
> 
> ```python
> class Dog(SQLAlchemyObjectType):
>     class Meta:
>         model = DogModel
>         interfaces = (relay.Node,)
> 
> ...
>
> class Query(graphene.ObjectType):
>    all_dogs = ExtendedSQLAlchemyConnectionField(Dog.connection)
> ```

Very nice! However, @neriusmika's simpler approach in https://github.com/graphql-python/graphene-sqlalchemy/issues/58#issuecomment-329379415 of defining just a custom standalone `CountableConnection `, along with (repeatedly 😢) declaring its usage in, e.g.:

```python
class Dog(SQLAlchemyObjectType):
    class Meta:
        model = DogModel
        interfaces = (relay.Node,)
        # explicitly define the connection
        connection_class = CountableConnection
```

...and the standard:

```python
class Query(graphene.ObjectType):
    all_dogs = SQLAlchemyConnectionField(Dog.connection)
    all_employees = SQLAlchemyConnectionField(Employee.connection)
```

...seems to have the added benefit of providing `totalCount` in nested connections as well? Like:

```graphql
query {
  allEmployees {
    # totalCount supported with both ExtendedSQLAlchemyConnectionField
    # and connection_class=CountableConnection
    totalCount
    edges {
      node {
        name
        dogs {
          # totalCount not supported with ExtendedSQLAlchemyConnectionField,
          # but supported with connection_class=CountableConnection
          totalCount
          edges {
            node {
              name
            }
          }
        }
      }
    }
  }
}
```

Maybe this won't work for top-level convenience helpers. But for just `totalCount` it's surely nice to have it available in nested connections as well.

(All thanks for the examples!)

**Comment by himat** [comment]
This didn't work for me, I get `AssertionError: The type X doesn't have a connection`

**Comment by ShantanuJoshi** [comment]
> This didn't work for me, I get `AssertionError: The type X doesn't have a connection`

Getting this same issue as well. Exact same model setup

**Comment by ShantanuJoshi** [comment]
> This didn't work for me, I get `AssertionError: The type X doesn't have a connection`

I had this issue because my mappings did not have `Base.query = db_session.query_property()` where db_session is `db_session = scoped_session(sessionmaker(autocommit=False, autoflush=False, bind=engine))` and define the engine in the mapping as well.

**Comment by ShantanuJoshi** [comment]
> This didn't work for me, I get `AssertionError: The type X doesn't have a connection`

Dude figured this out you need the beta version: https://github.com/graphql-python/graphene-sqlalchemy/issues/272

**Comment by erikwrede** [comment]
Closing this as the implementation of such a feature seems to be possible. It might be handy to add the recipe presented here to the docs/examples. I'll link this in a separate issue. If you feel that this should be a default feature instead of a manual recipe, please comment there :)
