### ISSUE TITLE
Hide certain fields in a model

### ISSUE THREAD

**Issue by Perlkonig** [graphql-python/graphene-sqlalchemy#62]
Is there a simple way to flag certain fields in a model as "private" or otherwise hidden? There are some fields that, authenticated or not, I never want passed via GraphQL query.

**Comment by earlgreyz** [comment]
You can use `exclude_fields` in `SQLAlchemyObjectType`. Lets say you want to hide `private_field` and `another_private_field` on `Example` (your SQLAlchemy model).
```python
from graphene_sqlalchemy import SQLAlchemyObjectType
from .models import Example as ExampleModel

class Example(SQLAlchemyObjectType):
    class Meta:
        model = ExampleModel
        exclude_fields = ('private_field', 'another_private_field', )
```

**Comment by waxisien** [comment]
There is also its opposite `only_fields` which works the same way.

**Comment by Perlkonig** [comment]
Thank you!

**Comment by ygbourhis** [comment]
This is honestly a serious lack in the documentation, could it be added?
Thanks

**Comment by mostafaghadimi** [comment]
How to hide certain fields of foreign key in the same way?

Imagine that we have the following `Post` model which has foreign key to the `User` model.
