### ISSUE TITLE
Detecting mutations

### ISSUE THREAD

**Issue by Perlkonig** [graphql-python/graphene-sqlalchemy#64]
I want to ensure that queries submitted via GET never attempt to mutate. When a query comes in, how can I detect whether it includes a mutation? Is there a clean, unambiguous way?

I apologize if this is an inappropriate place for such questions. I don't see links to a forum or anything. I appreciate your time.

**Comment by erikwrede** [comment]
The original request for queries is accessible via the `info` field of the resolver method.

```
def resolve_myType(parent, info, **kwargs):
   print(info.context)

>>> {'request': <starlette.requests.Request object at 0x00000184E519FDF0>, 'background': <starlette.background.BackgroundTasks object at 0x00000184E519FE50>}
``` 
In this case, I'm using a Starlette Webserver, so I could read the Request object to find out the request method. If the resolver is in a mutation, the mutation could then be blocked. 
Other GQL-Middlewares could work differently, check your individual GQL server for that. If there are a lot of mutations, the graphql-server should be modified instead to reduce redundancies.
