### ISSUE TITLE
Subclassing Connection in 2.0

### ISSUE THREAD

**Issue by neriusmika** [graphql-python/graphene-sqlalchemy#65]
Hi, in 2.0dev version I can't see the way to subclass `relay.Connection`. Because SQLAlchemyObjectType doesn't have a Connection attribute, the only way I see is to pass connection via the Meta class. Otherwise the connection is automatically created with default Connection class. But I can't specify the subclassed connection in Meta, because it needs a node attribute and I get circular reference. E. g.

```python
class UserConnection(graphene.relay.Connection):
    class Meta:
        node = User

class User(SQLAlchemyObjectType):
    class Meta:
        model = UserModel
        interfaces = (relay.Node, )
        connection = UserConnection
```

So I don't understand what's the point of connection parameter in SQLAlchemyObjectType Meta class? To make it work, I have changed SQLAlchemyObjectType.\_\_init_subclass_with_meta_\_ and introduced connection_type parameter. Now I can make an abstract subclassed Connection and pass it to Meta:

```python
class SQLAlchemyObjectType(ObjectType):
    @classmethod
    def __init_subclass_with_meta__(cls, model=None, registry=None, skip_registry=False,
                                    only_fields=(), exclude_fields=(), connection=None, connection_type=None,
                                    use_connection=None, interfaces=(), id=None, **options):

        ...

        if use_connection and not connection:
            # We create the connection automatically
            connection = (connection_type or Connection).create_type('{}Connection'.format(cls.__name__), node=cls) 

        ...
```

```python
class UserConnection(graphene.relay.Connection):
    class Meta:
        abstract = True


class User(SQLAlchemyObjectType):
    class Meta:
        model = UserModel
        interfaces = (relay.Node, )
        connection_type = UserConnection
```

Maybe I don't understand something and there is an easier way to make it work?

**Comment by richmondwang** [comment]
I am also having trouble with this as I am adding custom specification for my connections.
This "feature" would be nice and (very) helpful to have.

**Comment by neriusmika** [comment]
Based on your example, you can try this code, but I did not check it:

```python
import graphene
from graphene.relay import Node
from graphene_sqlalchemy import SQLAlchemyObjectType, SQLAlchemyConnectionField
from myapp import models


class CountableConnection(graphene.relay.Connection):
    class Meta:
        abstract = True

    total_count = graphene.Int()

    @staticmethod
    def resolve_total_count(root, info):
        return root.length

graphene.relay.Connection = CountableConnection


class Contact(SQLAlchemyObjectType, interfaces=[Node]):
    class Meta:
        model = models.Contact


class User(SQLAlchemyObjectType, interfaces=[Node]):
    class Meta:
        model = models.User
        

class Query(graphene.ObjectType):
    node = Node.Field()

    all_users = SQLAlchemyConnectionField(User)
```

**Comment by geertjanvdk** [comment]
@neriusmika Your fix is great and this is a fix that was done for the Django-version as well. Best would be to rename `connection_type` to `connection_class`.

**Comment by nikordaris** [comment]
I just submitted #120 which should fix this issue
