### ISSUE TITLE
Filter on the backend

### ISSUE THREAD

**Issue by tylfin** [graphql-python/graphene-sqlalchemy#66]
Given I have: an authenticated user, a model type that extends `SQLAlchemyObjectType`, and a `SQLAlchemyConnectionField` defined in my `Query`, how can I restrict the returned objects to only rows that have a relationship with this user?

**Comment by earlgreyz** [comment]
You can ovverrid a `resolve_` method for your `SQLAlchemyConnectionField` and apply desired filters

```python
class Something(SQLAlchemyObjectType):
    class Meta:
        model = SomethingModel

class Query(graphene.ObjectType):
    something = SQLAlchemyConnectionField(Something)
    
    def resolve_something(self, args, context, info):
        query = Something.get_query(context)
        return query.filter(SomethingModel.user_id == authenticated_user.id)
```

**Comment by tylfin** [comment]
Thanks!
