### ISSUE TITLE
Database ID

### ISSUE THREAD

**Issue by navinesh** [graphql-python/graphene-sqlalchemy#80]
1. Is there a way to get/map database id so that you can get this value in query?

2. Can we map only selected fields from the database table instead of all by default?

**Comment by navinesh** [comment]
I have managed to figure out no.2

I am just struggling with no.1

**Comment by navinesh** [comment]
I have managed to figure out no.1 as well.

**Comment by mplis** [comment]
@navinesh Would you mind putting your solution here? I'm curious how you solved these problems.

**Comment by navinesh** [comment]
For 1 I have a  DatabaseId class 

`class DatabaseId(graphene.Interface):
      db_id = Int()`

and use it in the interface as shown in the code below. I then map the database id as db_id

For 2 I have used only_fields to select the fields I want

`class User(SQLAlchemyObjectType):
    class Meta:
        model = UserModel
        interfaces = (relay.Node, DatabaseId)
        model.db_id = model.id
        only_fields = [
            'id', 'othernames', 'surname', 'email', 'designation', 'gender',
            'date_of_birth', 'annual', 'sick', 'bereavement', 'christmas',
            'maternity', 'isArchived', 'archiveReason', 'userupdates',
            'leaverecord'
        ]`

**Comment by navinesh** [comment]
I have defined a `DatabaseId` interface

```
class DatabaseId(graphene.Interface):
    db_id = Int()
```

`Class User` is an implementation of that interface. I then map the database id as `db_id` and used only_fields to select the fields I want.

```
class User(SQLAlchemyObjectType):
    class Meta:
        model = UserModel
        interfaces = (relay.Node, DatabaseId)
        model.db_id = model.id
        only_fields = [
            'id', 'othernames', 'surname', 'email'
        ]
```

**Comment by navinesh** [comment]
This is another way to map database id and select fields

```python
class User(SQLAlchemyObjectType):
    class Meta:
        model = UserModel
        interfaces = (relay.Node,)
        only_fields = [
            'id', 'othernames', 'surname', 'email'
        ]

    db_id = graphene.Int()

    @resolve_only_args
    def resolve_db_id(self):
        return self.id
```

**Comment by navinesh** [comment]
We can also use `from_global_id` to convert GraphQL id to database id - we don't have to create additional interface and map database id manually as per the two solutions above.

```python
from graphql_relay import from_global_id

database_id = from_global_id(args.get('GRAPHQL_ID'))[1]
```

**Comment by sreerajkksd** [comment]
resolve_only_args is deprecated in graphene 2.0 as per https://github.com/graphql-python/graphene/blob/master/UPGRADE-v2.0.md. We can do something like this instead:

```python
class User(SQLAlchemyObjectType):
    class Meta:
        model = UserModel
        interfaces = (relay.Node,)
        only_fields = [
            'id', 'othernames', 'surname', 'email'
        ]

    db_id = graphene.Int()

    def resolve_db_id(root, info):
        return root.id
```
