### ISSUE TITLE
`convert_column_to_enum` doesn't work at all

### ISSUE THREAD

**Issue by philiptzou** [graphql-python/graphene-sqlalchemy#9]
This issue is related with three packages: `graphql-core`, `graphene` and `graphene-sqlalchemy`. Actually there are 2 separated problems related with the Enum type:
1. In `convert_column_to_enum`, the returned value should be an instance of `UnmountedType` but not a subclass of `UnmountedType`.
2. [ `ChoiceType` of `sqlalchemy_utils`](https://github.com/kvesteri/sqlalchemy-utils/blob/0.32.9/sqlalchemy_utils/types/choice.py) coerces the result to `Choice` type or Enum subclass type (depend on which `XxxxTypeImpl` it used). But it's more pain in ass since there's no way to override [`GraphQLEnumType`'s `serialize` method](https://github.com/graphql-python/graphql-core/blob/v0.5.2/graphql/type/definition.py#L474) like `GraphQLScalarType` did.

**Comment by philiptzou** [comment]
3 pull-requests were issued in all 3 repositories to fix this problem. Now my `ChoiceType` finally worked.

**Comment by richmondwang** [comment]
any updates on this issue?

**Comment by erikwrede** [comment]
This should be fixed on master.
