### ISSUE TITLE
How can I reference an enum type created by SqlAlchemy mapping ?

### ISSUE THREAD

**Issue by mariogarcia** [graphql-python/graphene-sqlalchemy#96]
Hi:

I would like to reuse an `Enum` type I've mapped in one class. Lets say I had the class `Patient`:

```python
class Patient(Base):
    __tablename__ = 'patients'
    id = Column(CHAR(32), default=generate_uuid, nullable=False, primary_key=True)
    name = Column(Text)
    sex = Column(Enum('MALE', 'FEMALE', name='Sex'), nullable=False)
```
```python
from graphene import relay
from graphene_sqlalchemy import SQLAlchemyObjectType

from app.models.patient import Patient as PatientModel


class Patient(SQLAlchemyObjectType):
    class Meta:
        model = PatientModel
        interfaces = (relay.Node,)
```

That is perfectly mapped to a `Sex` graphql type. But if I would like to create a new `Patient`, How can I reference the `Sex` enum type generated by `graphene-sqlalchemy` e.g in an input type ?

```python
class CreatePatient(relay.ClientIDMutation):
    class Input:
        name = graphene.String()
        sex = ???
```

BTW I'm using latest master branch version.

**Comment by sboisson** [comment]
I had the same problem and I used the following workaround:

- Use a standalone `enum.Enum` as the reference enum type (no inline definition)
- Wrap into a SQLAlchemy enum: `sqlalchemy.Enum(SexType, name='SexType’)`
- Reference the SQLAlchemy in the model
- Create graphene mappings (`graphene.Enum.from_enum` doesn’t work with SQLAlchemy):

```
SexType = graphene.Enum('SexType', model.SexType.__members__.items())

(...)
@convert_sqlalchemy_type.register(sqlalchemy.types.Enum)
def convert_enum_to_enum(type, column, registry=None):
    if type.name == 'SexType':
        return graphene.Field(
            SexType,
            description=getattr(column, 'doc', None),
            required=not(getattr(column, 'nullable', True)),
        )
    (...)

```

**Comment by mariogarcia** [comment]
Thanks @sboisson sounds good to me :+1:

**Comment by sboisson** [comment]
You're welcome! You might want to watch issue #78 for built-in support

**Comment by annshress** [comment]
Hi there! Do we have a better way to achieve this, now? apart from doing `if...else if`.

**Comment by erikwrede** [comment]
Since  #78 and #98 are merged, I expect this problem to be fixed.
@annshress, I don't know what you are referring to with `if...else if`. If your problem persists, please open a new issue, including an example of your Models. 🙂
